import type * as Types from '../../../graphql/types.graphql.d';

export type ApproveLoanMutationVariables = Types.Exact<{
  approveLoanId: Types.Scalars['String']['input'];
}>;


export type ApproveLoanMutation = { __typename: 'Mutation', approveLoan: { __typename: 'Loan', id: string, code: string, customerId: string, customerCidNumber: string | null, workspaceBranchId: string | null, signature: string | null, amount: number, packageId: string, packagePeriodDays: number, assetType: Types.LoanAssetType, assetData: any | null, status: Types.LoanStatus, rejectReason: string | null, createdAt: number | null, nextReceiptAt: number | null, isHasLateInterestReceipt: boolean | null, isLiquidated: boolean | null, fulfilledAt: number | null, customer: { __typename: 'Customer', _id: string, name: string, code: string, phone: string | null, avatar: string | null }, workspaceBranch: { __typename: 'WorkspaceBranch', _id: string, name: string, hotline: string | null, location: { __typename: 'Location', provinceId: string | null, districtId: string | null, wardId: string | null, address: string | null, coordinates: { __typename: 'Coordinates', lat: number, lng: number } | null }, settings: { __typename: 'WorkspaceBranchSettings', bankAccount: { __typename: 'PluginBankAccount', bankId: number, accountNumber: string, accountName: string | null } | null } | null } | null, package: { __typename: 'LoanPackage', id: string, assetTypes: Array<Types.LoanAssetType>, type: Types.LoanPackageType, days: number, contractFee: number, unFixedCapitalRates: Array<Array<number>>, liquidationFeeRate: number | null, periodDaysOptions: Array<number>, lateInterestRates: Array<{ __typename: 'LateInterestRate', lateDays: number, rate: number }> }, paymentPeriods: Array<{ __typename: 'LoanPaymentPeriod', period: number, startTime: number, endTime: number, totalAmount: number, fee: number, capitalAmount: number, remainCapitalAmount: number, note: string | null }> | null, paymentProgress: Array<{ __typename: 'LoanPaymentProgress', receiptId: string, amount: number, time: number | null, isCompleted: boolean }> | null, metadata: { __typename: 'LoanMetadata', cidNumber: string | null, cidVnLocation: { __typename: 'Location', provinceId: string | null, districtId: string | null, wardId: string | null, address: string | null, coordinates: { __typename: 'Coordinates', lat: number, lng: number } | null } | null, cidLocation: { __typename: 'Location', provinceId: string | null, districtId: string | null, wardId: string | null, address: string | null, coordinates: { __typename: 'Coordinates', lat: number, lng: number } | null } | null } | null, payment: { __typename: 'LoanPayment', accountName: string, accountNumber: string, accountBankId: string } | null, coord: { __typename: 'Coordinates', lat: number, lng: number } | null } };


import { TypedDocumentNode } from '@apollo/client/core';
export const ApproveLoanDocument = (import("graphql").DocumentNode) as TypedDocumentNode<ApproveLoanMutation, ApproveLoanMutationVariables>;
export default ApproveLoanDocument 