query Loans(
  $customerCidNumber: String
  $status: [LoanStatus!]
  $limit: Float
  $offset: Float
  $sortCreatedAt: SortDirection
  $query: JSONObject
) {
  list: loans(
    customerCidNumber: $customerCidNumber
    status: $status
    limit: $limit
    offset: $offset
    sortCreatedAt: $sortCreatedAt
    query: $query
  ) {
    total
    results {
      id
      code
      customerId
      customerCidNumber
      customer {
        _id
        name
      }
      workspaceBranchId
      amount
      packageId
      package
      packagePeriodDays
      paymentPeriods
      assetType
      assetData
      paymentProgress
      metadata
      status
      rejectReason
      payment
      createdAt
      nextReceiptAt
      isHasLateInterestReceipt
      isLiquidated
      fulfilledAt
    }
  }
}
