#import "../../workspace-members/graphql/fragmentWorkspaceMember.graphql"

fragment TaskData on Task {
  _id
  code
  name
  description
  status
  order

  childCount
  childOrder {
    first
    last
  }
  childTimeline {
    startDate
    dueDate
  }

  startDate
  dueDate
  estimatedTime

  priority
  progress
  childProgress

  partners {
    _id
    name
    logo
  }

  assigneeUsers {
    ...WorkspaceMemberData
  }

  customer {
    _id
    name
    avatar
    phone
  }

  parentId
  parent {
    _id
    name
    code
    order

    folderId
    folder {
      _id
      color
      name
      slug
    }
  }

  tags {
    _id
    color
    name
  }

  folderId
  folder {
    _id
    color
    name
    slug
  }

  timeTrackings {
    id
    workspaceId
    userId
    user {
      _id
      name
      color
      avatar
    }
    billable
    note
    startAt
    endAt
  }

  statuses {
    id
    name
    color
    order
  }

  createdAt
  isArchived
}
