#import "./fragmentTask.graphql"

query Tasks(
  $folderId: String
  $parentId: String
  $status: String
  $offset: Float
  $limit: Float
  $ids: [String!]
  $assigneeUserIds: [String!]
  $partnerIds: [String!]
  $tagIds: [String!]
  $priority: TaskPriority
  $all: Boolean
  $isProgressOnly: Boolean
  $isClosedOnly: Boolean
  $fromTrackingTime: Float
  $toTrackingTime: Float
) {
  tasks(
    folderId: $folderId
    parentId: $parentId
    status: $status
    offset: $offset
    limit: $limit
    ids: $ids
    assigneeUserIds: $assigneeUserIds
    partnerIds: $partnerIds
    tagIds: $tagIds
    priority: $priority
    all: $all
    isProgressOnly: $isProgressOnly
    isClosedOnly: $isClosedOnly
    fromTrackingTime: $fromTrackingTime
    toTrackingTime: $toTrackingTime
  ) {
    total
    results {
      ...Task      
    }
  }
}
