import type * as Types from '../../../graphql/types.graphql.d';

export type TaskByIdQueryVariables = Types.Exact<{
  id: Types.Scalars['String']['input'];
}>;


export type TaskByIdQuery = { __typename: 'Query', task: { __typename: 'Task', _id: string, code: string, name: string, description: string | null, status: string, order: number, childCount: number, startDate: number | null, dueDate: number | null, estimatedTime: number | null, childEstimatedTime: number | null, priority: Types.TaskPriority | null, progress: number, childProgress: number, parentId: string | null, folderId: string | null, createdAt: number | null, isArchived: boolean | null, childOrder: { __typename: 'TaskChildOrder', first: number | null, last: number | null }, childTimeline: { __typename: 'TaskChildTimeline', startDate: number | null, dueDate: number | null } | null, partners: Array<{ __typename: 'PartnerEntity', _id: string, name: string, logo: string | null }>, assigneeUsers: Array<{ __typename: 'WorkspaceMember', _id: string, userId: string, name: string, color: string | null, avatar: string | null, memberId: string | null, roles: Array<{ __typename: 'WorkspaceMemberRole', _id: string, name: string, color: string | null }> }>, customer: { __typename: 'Customer', _id: string, code: string, name: string, avatar: string | null, phone: string | null } | null, parent: { __typename: 'Task', _id: string, name: string, code: string, order: number, folderId: string | null, folder: { __typename: 'Tag', _id: string, color: string | null, name: string, slug: string } | null } | null, tags: Array<{ __typename: 'Tag', _id: string, color: string | null, name: string }>, folder: { __typename: 'Tag', _id: string, color: string | null, name: string, slug: string } | null, timeTrackings: Array<{ __typename: 'TaskTimeTracking', id: string, workspaceId: string, userId: string, billable: boolean | null, note: string | null, startAt: number, endAt: number | null, user: { __typename: 'WorkspaceMember', _id: string, userId: string, name: string, color: string | null, avatar: string | null } | null }> | null, statuses: Array<{ __typename: 'TaskStatus', id: string, name: string | null, color: string | null, order: number, contextId: string | null, contextType: Types.TaskContextType | null }> } };

declare const Document: import("graphql").DocumentNode; export default Document;