query Search($query: String!, $entities: [String!], $limit: Int) {
  search(query: $query, entities: $entities, limit: $limit) {
    id
    entity
    ... on SearchResultOrders {
      code
    }
    ... on SearchResultTags {
      name
      type
    }
    ... on SearchResultPrescriptions {
      name
      note
    }
    ... on SearchResultReceipt {
      code
      note
    }
    ... on SearchResultTask {
      name
      code
    }
    ... on SearchResultWorkspaceMember {
      name
      email
      avatar
      phone
      color
      userId
      memberId
    }
    ... on SearchResultCustomer {
      name
      code
      phone
      avatar
    }
    ... on SearchResultProduct {
      name
      type
    }
    ... on SearchResultPartner {
      name
      phone
    }
    ... on SearchResultCategory {
      name
    }
    ... on SearchResultLoan {
      code
      customerName
      customerPhone
      imeil
      status
    }
  }
}
