#import "./fragmentBooking.graphql"

mutation CreateBooking(
  $startTime: Float!
  $endTime: Float!
  $status: BookingStatus!
  $title: String
  $note: String
  $reasonForCancellation: String
  $assigneeUserIds: [String!]
  $customerId: String
  $createdAt: Float
  $workspaceBranchId: String
) {
  createBooking(
    startTime: $startTime
    endTime: $endTime
    status: $status
    title: $title
    note: $note
    reasonForCancellation: $reasonForCancellation
    assigneeUserIds: $assigneeUserIds
    customerId: $customerId
    createdAt: $createdAt
    workspaceBranchId: $workspaceBranchId
  ) {
    ...BookingData
  }
}
