#import "../../workspace-members/graphql/fragmentWorkspaceMember.graphql"

fragment AttendanceRecord on AttendanceRecord {
  _id
  refs
  deviceId
  userId
  workspaceId
  time
  type
  method
  status
  locationCoordinates {
    lat
    lng
  }
  photoUrl
  note
  rejectedReason
  member {
    ...WorkspaceMember
  }
  device {
    _id
    deviceName
  }
  location {
    name
    coordinates {
      lat
      lng
    }
  }
  approvedAt
  approvedBy {
    _id
    name
  }
  rejectedAt
  rejectedBy {
    _id
    name
  }
}
