type ActivitiesPaginated {
  results: [Activity!]!
  total: Float!
}

type Activity {
  _id: String!
  childCount: Float
  content: String
  contentLastModifiedAt: Float
  contextId: String!
  contextType: String!
  createdAt: Float
  createdByUser: WorkspaceMember!
  data: JSONObject
  isPinned: Boolean
  parentId: String
  pinnedAt: Float
  pinnedByUser: WorkspaceMember!
  pinnedByUserId: String
  reactionsCount: ReactionsCount!
  type: ActivityType!
  updatedAt: Float
}

"""Available activity types"""
enum ActivityType {
  COMMENT
  COMMON
}

"""The `AnyType` scalar type represents any value without restrictions."""
scalar AnyType

type AppConfig {
  UTC: String!
  firebase: FirebaseClientConfig!
  metaAppId: String!
  metaAppScope: [String!]!
  metaAppVersion: String!
  name: String!
  timeZone: String!
  version: String!
  workspaceDomainIP: String!
  zaloAppId: String!
}

"""Available locales"""
enum AppLocale {
  EN
  VI
}

type BaseCustomFieldValue {
  customFieldId: String!
  value: AnyType
}

type Booking {
  _id: String!
  assigneeUserIds: [String!]!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  customerId: String
  endTime: Float!
  note: String
  reasonForCancellation: String
  refs: [String!]
  startTime: Float!
  status: BookingStatus!
  title: String
  transferToBookingId: String
  updatedAt: Float
  workspaceId: String!
}

"""Booking statuses"""
enum BookingStatus {
  CANCELLED
  CHECK_IN
  COMPLETED
  IN_PROGRESS
  JUST_CREATED
  RESCHEDULED
}

type BookingsPaginated {
  results: [Booking!]!
  total: Float!
}

type CategoriesPaginated {
  results: [Category!]!
  total: Float!
}

type Category {
  _id: String!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  customFields: [CustomField!]!
  description: String
  icon: String
  name: String!
  order: Float!
  parentId: String
  refs: [String!]
  slug: String!
  thumbnail: String
  type: CategoryType!
  updatedAt: Float
}

"""Available category types"""
enum CategoryType {
  COMMON
  POSTS
  PRODUCTS
}

type ConfigTaskStatuses {
  isInherited: Boolean!
  statuses: [TaskStatus!]!
  workspaceStatuses: [TaskStatus!]!
}

type Coordinates {
  lat: Float!
  lng: Float!
}

input CoordinatesInput {
  lat: Float!
  lng: Float!
}

type Coupon {
  _id: String!
  code: String
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  customerId: String
  expiredAt: Float
  isExpired: Boolean
  quantity: Float!
  receiptId: String
  refs: [String!]
  rule: CouponRule!
  ruleId: String!
  ticketId: String
  updatedAt: Float
}

type CouponRule {
  _id: String!
  benefits: [CouponRuleBenefit!]!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  description: String
  image: String
  isActive: Boolean!
  isCumulative: Boolean!
  name: String!
  refs: [String!]
  terms: [CouponRuleTerm!]!
  updatedAt: Float
}

type CouponRuleBenefit {
  data: AnyType!
  type: CouponRuleBenefitType!
}

"""Available coupon rule benefit types"""
enum CouponRuleBenefitType {
  DISCOUNT_ON_PRODUCT
  DISCOUNT_ON_TOTAL
  FREE_ON_PRODUCT
}

type CouponRuleTerm {
  data: AnyType!
  type: CouponRuleTermType!
}

"""Available coupon rule term types"""
enum CouponRuleTermType {
  LIMIT_PRODUCTS
  MINIMUM_TOTAL
}

type CouponRulesPaginated {
  results: [CouponRule!]!
  total: Float!
}

type CouponsPaginated {
  results: [Coupon!]!
  total: Float!
}

input CreateTaskInput {
  _id: String
  assigneeUserIds: [String!]
  customerId: String
  description: String
  dueDate: Float
  estimatedTime: Float
  folderId: String
  isArchived: Boolean
  name: String
  order: Float
  parentId: String
  partnerIds: [String!]
  points: Float
  priority: TaskPriority
  startDate: Float
  status: String
  tagIds: [String!]
  timeTrackings: [TaskTimeTrackingInput!]
  workspaceBranchId: String
}

type CustomField {
  _id: String!
  config: JSONObject
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  description: String
  entities: [String!]!
  key: String
  label: String!
  order: Float!
  placeholder: String
  refs: [String!]
  type: CustomFieldType!
  updatedAt: Float
}

"""Available custom field types"""
enum CustomFieldType {
  DATE
  FILE
  MULTI_SELECT
  NUMBER
  SELECT
  SWITCH
  TEXT
  TEXTAREA
}

type CustomFieldValue {
  config: JSONObject
  customFieldId: String!
  key: String
  type: CustomFieldType!
  value: AnyType
}

input CustomFieldValueInput {
  customFieldId: String!
  value: AnyType
}

type CustomFieldsPaginated {
  results: [CustomField!]!
  total: Float!
}

type Customer {
  _id: String!
  assigneeUserIds: [String!]
  avatar: String
  birthday: Float
  birthdayDate: Float
  birthdayMonth: Float
  code: String!
  codePrefix: String
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  email: String
  gender: Gender
  location: LocationEntity
  medicalHistory: [String!]
  name: String!
  phone: String
  plainCode: String
  presenterCustomerId: String
  refs: [String!]
  relatedCustomerIds: [String!]
  salaryAmount: Float
  secondaryLocation: LocationEntity
  tagIds: [String!]
  updatedAt: Float
  vnLocation: LocationEntity
  vnSecondaryLocation: LocationEntity
}

type CustomerForm {
  _id: String!
  cancelReason: String
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  dynamicData: AnyType
  email: String
  location: LocationEntity
  name: String!
  phone: String!
  refs: [String!]
  status: CustomerFormStatus!
  updatedAt: Float
  vnLocation: LocationEntity
  workspaceBranch: WorkspaceBranch
}

"""Available customer form statuses"""
enum CustomerFormStatus {
  CANCELLED
  COMPLETED
  PENDING
}

type CustomerFormsPaginated {
  results: [CustomerForm!]!
  total: Float!
}

type CustomersPaginated {
  results: [Customer!]!
  total: Float!
}

type DeviceEntity {
  _id: String!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  identifyId: String
  lastActiveAt: Float!
  locale: AppLocale
  notificationToken: String
  refs: [String!]
  updatedAt: Float
  userAgent: String!
  userId: String
}

type EInvoice {
  _id: String!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  invoiceData: JSONObject
  invoiceId: String!
  isCancelled: Boolean
  provider: PluginEInvoicesProviderType!
  providerData: JSONObject
  providerId: String!
  receiptCode: String!
  receiptId: String!
  refs: [String!]
  updatedAt: Float
  url: String
}

type Event {
  _id: String!
  actionType: EventDataActionType
  channel: EventChannel
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  data: JSONObject
  persist: Boolean
  ref: String
  refs: [String!]
  sessionId: String
  time: Float!
  type: EventType!
  updatedAt: Float
  user: WorkspaceMember!
  userId: String
  variant: EventVariant
}

"""Available event channels"""
enum EventChannel {
  NONE
  PERSONAL
  WORKSPACE
}

"""Available event data action types"""
enum EventDataActionType {
  ARCHIVED
  CREATE
  UPDATE
}

"""Available event types"""
enum EventType {
  ACTIVITY_ARCHIVED
  ACTIVITY_NEW
  ACTIVITY_SYNCED
  ACTIVITY_UPDATED
  BANK_TRANSACTION_CANCELLED
  BANK_TRANSACTION_FAILED
  BANK_TRANSACTION_FULFILLED
  BANK_TRANSACTION_PAID
  BOOKING_CANCELLED
  BOOKING_CHECKIN
  BOOKING_COMPLETED
  BOOKING_IN_PROGRESS
  BOOKING_NEW
  BOOKING_UPDATED
  CATEGORY_ARCHIVED
  CATEGORY_NEW
  CATEGORY_UPDATED
  COMMENT_NEW
  COMMENT_PINNED
  COMMENT_REMOVED
  COMMENT_UNPINNED
  COMMENT_UPDATED
  COUPONS_CREATED
  COUPONS_USED
  COUPON_RULES_ARCHIVED
  COUPON_RULES_CREATED
  COUPON_RULES_UPDATED
  CUSTOMER_ARCHIVED
  CUSTOMER_ASSIGN_TO_USER
  CUSTOMER_BULK_UPDATE_WORKSPACE_BRANCH
  CUSTOMER_CONTACTS_UPDATED
  CUSTOMER_FORM_ARCHIVED
  CUSTOMER_FORM_NEW
  CUSTOMER_FORM_UPDATED
  CUSTOMER_KYC_APPROVED
  CUSTOMER_KYC_PENDING
  CUSTOMER_KYC_REJECTED
  CUSTOMER_NEW
  CUSTOMER_UNASSIGN_USER
  CUSTOMER_UPDATED
  CUSTOM_FIELDS_NEW
  CUSTOM_FIELDS_REMOVED
  CUSTOM_FIELDS_UPDATED
  E_INVOICE_CREATED
  E_INVOICE_REMOVED
  FILE_NEW
  FILE_REMOVED
  HRM_TIMEKEEPING_MANUAL_APPROVAL
  HRM_TIMEKEEPING_MEMBER_CHECK_IN
  HRM_TIMEKEEPING_MEMBER_CHECK_OUT
  HRM_TIMEKEEPING_REJECTED
  HRM_TIMEKEEPING_REMOVED
  LOANS_APPROVED
  LOANS_APPROVED_REVERTED
  LOANS_ARCHIVED
  LOANS_CHANGE_WORKSPACE_BRANCH
  LOANS_COMPLETED
  LOANS_FULFILLED
  LOANS_FULFILLED_REVERTED
  LOANS_JUST_CREATED
  LOANS_LIQUIDATION
  LOANS_PENDING
  LOANS_REJECTED
  LOANS_REVERT_LIQUIDATION
  LOANS_REVERT_REJECTED
  LOANS_SYNCED
  LOANS_UPDATED
  MESSAGE_BOX_CLOSED
  MESSAGE_BOX_IN_PROGRESS
  MESSAGE_BOX_NEW
  MESSAGE_BOX_NEW_MESSAGE
  MESSAGE_BOX_REMOVED
  MESSAGE_BOX_UPDATED
  MESSAGE_BOX_WAITING
  MESSAGE_NEW
  MESSAGE_UPDATED
  NOTIFICATION_CLEANED
  NOTIFICATION_LIST_VIEWED
  NOTIFICATION_NEW
  NOTIFICATION_READED
  ORDER_ARCHIVED
  ORDER_NEW
  ORDER_SYNCED
  ORDER_UPDATED
  PARTNER_ARCHIVED
  PARTNER_NEW
  PARTNER_UPDATED
  PLUGIN_AI_ASSISTANTS_NEW
  PLUGIN_AI_ASSISTANTS_REMOVED
  PLUGIN_AI_ASSISTANTS_UPDATED
  PLUGIN_MESSAGE_HUBS_NEW
  PLUGIN_MESSAGE_HUBS_REMOVED
  PLUGIN_MESSAGE_HUBS_UPDATED
  PLUGIN_META_PAGES_DISCONNECTED
  PLUGIN_META_PAGES_UPDATED
  PLUGIN_ZALO_OA_ACTIVE
  PLUGIN_ZALO_OA_DISABLED
  PLUGIN_ZALO_OA_ENABLED
  PLUGIN_ZALO_OA_INACTIVE
  PLUGIN_ZALO_OA_UPDATED
  POST_ARCHIVED
  POST_NEW
  POST_UPDATED
  PRESCRIPTIONS_NEW
  PRESCRIPTIONS_REMOVED
  PRESCRIPTIONS_UPDATED
  PRODUCT_ARCHIVED
  PRODUCT_COMBO_NEW
  PRODUCT_COMBO_UPDATE
  PRODUCT_NEW
  PRODUCT_STOCK_IN
  PRODUCT_STOCK_IN_MULTIPLE
  PRODUCT_STOCK_IN_REVERT
  PRODUCT_STOCK_OUT
  PRODUCT_STOCK_OUT_REVERT
  PRODUCT_SUPPLY_RECORD_NEW
  PRODUCT_UPDATE
  PRODUCT_VOUCHERS_NEW
  PROMOTION_ARCHIVED
  PROMOTION_NEW
  PROMOTION_UPDATED
  REACTION_ADDED
  REACTION_REMOVED
  RECEIPT_ARCHIVED
  RECEIPT_CHANGE_WORKSPACE_BRANCH
  RECEIPT_DISBURSEMENT
  RECEIPT_NEW
  RECEIPT_PAID
  RECEIPT_REVERT_PAYMENT
  RECEIPT_SYNCED
  RECEIPT_UNARCHIVED
  RECEIPT_UPDATED
  REPORT_RANGE_SYNCED
  REPORT_REALTIME_SYNCED
  TABLE_SLOT_ARCHIVED
  TABLE_SLOT_NEW
  TABLE_SLOT_UPDATED
  TAGS_ARCHIVED
  TAGS_UPDATED
  TAG_NEW
  TASKS_UPDATED
  TASK_ARCHIVED
  TASK_ASSIGNED
  TASK_DESCRIPTION_UPDATED
  TASK_METRIC_SYNCED
  TASK_NAME_UPDATED
  TASK_NEW
  TASK_PRIORITY_UPDATED
  TASK_STATUS_UPDATED
  TASK_SYNCED
  USER_OFFLINE
  USER_ONLINE
  USER_PROFILE_UPDATED
  WORKSPACE_API_APP_ARCHIVED
  WORKSPACE_API_APP_CREATED
  WORKSPACE_API_APP_UPDATED
  WORKSPACE_ARCHIVED
  WORKSPACE_BILLINGS_CASHBACK_NEW
  WORKSPACE_BILLINGS_DEPOSITED
  WORKSPACE_BILLINGS_PAYMENT_NEW
  WORKSPACE_BILLINGS_PAYMENT_PAID
  WORKSPACE_BILLINGS_WITHDRAWN
  WORKSPACE_BRANCH_ARCHIVED
  WORKSPACE_BRANCH_NEW
  WORKSPACE_BRANCH_UPDATED
  WORKSPACE_INVITE_CODE_UPDATED
  WORKSPACE_MEMBER_ASSIGN_ROLES
  WORKSPACE_MEMBER_JOINED
  WORKSPACE_MEMBER_LEAVED
  WORKSPACE_MEMBER_OFFLINE
  WORKSPACE_MEMBER_ONLINE
  WORKSPACE_MEMBER_SYNCED
  WORKSPACE_MEMBER_TRANSFER_OWNER
  WORKSPACE_MEMBER_UPDATED
  WORKSPACE_NEW
  WORKSPACE_ROLES_NEW
  WORKSPACE_ROLES_REMOVED
  WORKSPACE_ROLES_UPDATED
  WORKSPACE_SETTING_UPDATED
  WORKSPACE_STATS_UPDATED
  WORKSPACE_SUBSCRIPTION_UPDATED
  WORKSPACE_UPDATED
}

"""Available event variants"""
enum EventVariant {
  INFO
  NEGATIVE
  POSITIVE
  WARNING
}

type EventsPaginated {
  results: [Event!]!
  total: Float!
}

type File {
  _id: String!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  externalUrl: String
  fileName: String!
  path: String!
  ref: String
  refs: [String!]
  relatedCustomerId: String
  relatedHrmTimekeepingId: String
  relatedMessageBoxId: String
  relatedMessageId: String
  relatedProductId: String
  relatedReceiptId: String
  relativePath: String
  size: Float
  thumbnail: String
  type: FileType!
  updatedAt: Float
  uploadByUserId: String
  url: String!
}

"""Available file types"""
enum FileType {
  AUDIO
  MS_EXCEL
  MS_POWERPOINT
  MS_WORD
  PDF
  PHOTO
  UNKNOWN
  VIDEO
}

type FilesPaginated {
  results: [File!]!
  total: Float!
}

type FirebaseClientConfig {
  apiKey: String!
  appId: String!
  authDomain: String!
  measurementId: String!
  messagingSenderId: String!
  projectId: String!
  storageBucket: String!
}

"""Available genders"""
enum Gender {
  FEMALE
  MALE
  OTHER
}

"""Available task statuses modes"""
enum GetTaskStatusesMode {
  EDIT
  VIEW
}

"""
The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSONObject

type Loan {
  _count: Float!
  _id: String
  amount: Float!
  assetData: AnyType
  assetType: LoanAssetType!
  code: String!
  coord: Coordinates
  createdAt: Float
  customFieldValues: [BaseCustomFieldValue!]
  customer: Customer!
  customerCidNumber: String
  customerId: String!
  fulfilledAt: Float
  id: String!
  isHasLateInterestReceipt: Boolean
  isLiquidated: Boolean
  metadata: AnyType
  nextReceiptAt: Float
  package: JSONObject!
  packageId: String!
  packagePeriodDays: Float!
  payment: AnyType
  paymentPeriods: AnyType
  paymentProgress: AnyType
  refs: [String!]
  rejectReason: String
  relatedEntities: [RelatedEntity!]
  signature: String
  status: LoanStatus!
  updatedAt: Float
  workspaceBranch: WorkspaceBranch
  workspaceBranchId: String
}

"""Available loan asset types"""
enum LoanAssetType {
  BUSINESS_PERMIT
  CAR_REGISTRATION
  ICLOUD
  LAND_CERTIFICATE
  MOTOBIKE_REGISTRATION
}

"""Available loan statuses"""
enum LoanStatus {
  APPROVED
  COMPLETED
  FULFILLED
  OVERDUE
  PENDING
  PENDING_SIGN
  REJECTED
}

type LoansPaginated {
  results: [Loan!]!
  total: Float!
}

type LocationEntity {
  address: String
  coordinates: Coordinates
  districtId: String
  provinceId: String
  wardId: String
}

input LocationInput {
  address: String
  coordinates: CoordinatesInput
  districtId: String
  provinceId: String
  wardId: String
}

type Mutation {
  addActivity(content: String, contextId: String!, contextType: String!, parentId: String, type: ActivityType!): Activity!
  addReaction(entity: String!, entityId: String!, type: ReactionType!): Boolean!
  archiveActivity(id: String!): Activity!
  assignWorkspaceMemberRoles(memberId: String!, roleIds: [String!]!): WorkspaceMember!
  bulkUpdateTags(items: [UpdateTagInput!]!): [Tag!]!
  bulkUpdateTasks(items: [UpdateTaskInput!]!): [Task!]!
  createCategory(customFieldValues: [CustomFieldValueInput!], description: String, icon: String, name: String!, order: Float, parentId: String, slug: String, thumbnail: String, type: CategoryType): Category!
  createProduct(categoryId: String, code: String, combos: [ProductComboInput!], combosExpireInDays: Float, content: String, customFieldValues: [CustomFieldValueInput!], defaultQtyPerUse: Float, displayName: String, image: String, isHiddenInReceiptWhenNoPrice: Boolean, isStockCheck: Boolean, maxPrice: Float, minPrice: Float, name: String!, price: Float!, productCode: String, supplies: [ProductSupplyInput!], tags: [String!], type: ProductType!, unit: String!, voucherAmount: Float, voucherExcludeProductIds: [String!], voucherExpireInDays: Float, voucherIncludeProductIds: [String!], warningOutOfDateBeforeDays: Float, warningOutOfStockQty: Float): Product!
  createTag(input: TagDto!): Tag!
  createTask(input: CreateTaskInput!): Task!
  createWorkspaceRole(color: String, description: String, name: String!, permissions: [String!]!): WorkspaceRole!
  deleteCategory(id: String!): Boolean!
  deleteWorkspaceRole(_id: String!): Boolean!
  duplicateTask(_id: String!, overwrite: CreateTaskInput): Task!
  externalStorageVerifyDna(dna: String!): File!
  fetchExternalStorageSize: Float!
  generateCategorySlug(name: String!): String!
  generateWorkspaceInviteCode: String!
  healthcheckPluginExternalStorage: Boolean!
  interactCategory(id: String!): Boolean!
  pluginExternalStorageSignUploadUrl(fileName: String!, id: String, refs: [String!]): SignUploadUrlResponse!
  registerDevice(input: RegisterDeviceDto!): DeviceEntity!
  removePluginExternalStorage: Boolean!
  removeReaction(entity: String!, entityId: String!, type: ReactionType!): Boolean!
  removeTag(id: String!): Boolean!
  setPluginExternalStorage(accessKeyId: String, bucketName: String, endpointUrl: String, provider: PluginExternalStorageProvider!, region: String, secretAccessKey: String): PluginExternalStorage!
  syncTask(_id: String!): SyncTaskResult!
  toggleDisablePluginExternalStorage: Boolean!
  updateActivity(content: String, id: String!): Activity!
  updateCategory(customFieldValues: [CustomFieldValueInput!], description: String, icon: String, id: String!, name: String!, order: Float, parentId: String, slug: String, thumbnail: String, type: CategoryType): Category!
  updateTaskStatuses(contextId: String, contextType: TaskContextType, isInherited: Boolean, statuses: [TaskStatusInput!]!): [TaskStatus!]!
  updateWorkspace(appColor: String, appColorShape: Float, appDomain: String, appIcon: String, appName: String, hotline: String, locale: AppLocale, location: LocationInput, logo: String, name: String!, phone: String, type: WorkspaceType!): Workspace!
  updateWorkspaceMember(color: String, displayName: String, memberId: String!, workingTimeType: WorkspaceMemberWorkingTimeType, workspaceBranchIds: [String!]): WorkspaceMember!
  updateWorkspaceRole(_id: String!, color: String, description: String, name: String!, permissions: [String!]!): WorkspaceRole!
}

type Order {
  _count: Float!
  _id: String
  assigneeUserIds: [String!]
  assigneeUsers: [WorkspaceMember!]!
  code: String!
  comboIds: [String!]
  couponIds: [String!]
  createdAt: Float
  createdByUser: WorkspaceMember!
  customFieldValues: [BaseCustomFieldValue!]
  discounts: [OrderDiscount!]!
  id: String!
  isFulfilled: Boolean
  items: AnyType!
  note: String
  paidAmount: Float!
  paymentStatus: OrderPaymentStatus!
  promotionIds: [String!]
  refs: [String!]
  relatedCustomer: Customer
  relatedCustomerId: String
  relatedEntities: [RelatedEntity!]
  relatedUserIds: [String!]
  totalAmount: Float!
  type: OrderType
  updatedAt: Float
  voucherIds: [String!]
}

type OrderDiscount {
  amount: Float!
  productComboId: String
  productCouponId: String
  productId: String
  productQuantity: Float
  productVoucherAmount: Float
  productVoucherId: String
  promotionId: String
  type: OrderDiscountType!
}

"""Order discount type"""
enum OrderDiscountType {
  COMBO
  COUPON
  DIRECT
  PROMOTION
  VOUCHER
}

"""Order payment status"""
enum OrderPaymentStatus {
  COMPLETED
  PROCESSING
}

"""Order type"""
enum OrderType {
  COMMON
}

type OrdersPaginated {
  results: [Order!]!
  total: Float!
}

type Partner {
  _id: String!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  email: String
  logo: String
  name: String!
  phone: String
  refs: [String!]
  updatedAt: Float
}

type PartnersPaginated {
  results: [Partner!]!
  total: Float!
}

type PluginEInvoicesPaginated {
  results: [EInvoice!]!
  total: Float!
}

"""Available plugin e-invoices provider types"""
enum PluginEInvoicesProviderType {
  MATBAO
  MATBAO_DEMO
}

type PluginExternalStorage {
  bucketName: String
  endpointUrl: String
  isDisabled: Boolean
  provider: PluginExternalStorageProvider!
  region: String
  size: Float
}

"""Available external storage providers"""
enum PluginExternalStorageProvider {
  AWS_S3
}

type Posts {
  _id: String!
  categoryId: String
  content: JSONObject
  contentHtml: String
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  excerpt: String
  meta: JSONObject
  productId: String
  publishedAt: Float
  refs: [String!]
  slug: String!
  thumbnail: String
  title: String!
  updatedAt: Float
}

type PostsPaginated {
  results: [Posts!]!
  total: Float!
}

type Prescription {
  _id: String!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  items: AnyType!
  name: String!
  note: String
  refs: [String!]
  updatedAt: Float
}

type PrescriptionsPaginated {
  results: [Prescription!]!
  total: Float!
}

type Product {
  _id: String!
  category: Category
  categoryId: String
  code: String
  combos: [ProductComboValue!]
  combosExpireInDays: Float
  content: String
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  defaultQtyPerUse: Float
  displayName: String
  image: String
  inStock: Float
  isHiddenInReceiptWhenNoPrice: Boolean
  isStockCheck: Boolean
  maxPrice: Float
  minPrice: Float
  name: String!
  price: Float!
  productCode: String
  refs: [String!]
  supplies: [ProductSupply!]
  tags: [String!]!
  type: ProductType!
  unit: String!
  updatedAt: Float
  voucherAmount: Float
  voucherExcludeProductIds: [String!]
  voucherExpireInDays: Float
  voucherIncludeProductIds: [String!]
  warningOutOfDateBeforeDays: Float
  warningOutOfStockQty: Float
  workspaceId: String!
}

type ProductCombo {
  _count: Float!
  _id: String
  createdAt: Float
  customFieldValues: [BaseCustomFieldValue!]
  customerId: String!
  expireAt: Float
  id: String!
  productId: String!
  productRefs: [ProductComboRef!]!
  refs: [String!]
  relatedEntities: [RelatedEntity!]
  sourceId: String!
  status: ProductComboStatus!
  updatedAt: Float
}

input ProductComboInput {
  productId: String!
  quantity: Float!
}

type ProductComboRef {
  productRefId: String!
  productRefRevenue: Float!
  quantity: Float!
  quantityUsed: Float!
}

"""Product combo status"""
enum ProductComboStatus {
  ACTIVE
  EXPIRED
  INACTIVE
  OUT_OF_STOCK
  SOURCE_UNAVAILABLE
}

type ProductComboValue {
  productId: String!
  quantity: Float!
}

type ProductCombosPaginated {
  results: [ProductCombo!]!
  total: Float!
}

type ProductStock {
  _count: Float!
  _id: String
  code: String
  costPrice: Float!
  createdAt: Float
  createdByUser: WorkspaceMember!
  customFieldValues: [BaseCustomFieldValue!]
  expireAt: Float!
  id: String!
  note: String
  product: Product!
  productId: String!
  quantity: Float!
  records: AnyType!
  refs: [String!]
  relatedEntities: [RelatedEntity!]
  remainQuantity: Float!
  updatedAt: Float
}

type ProductStockRecord {
  _count: Float!
  _id: String
  createdAt: Float
  createdByUser: WorkspaceMember
  customFieldValues: [BaseCustomFieldValue!]
  id: String!
  note: String
  product: Product!
  productId: String!
  productStockId: String!
  quantity: Float!
  ref: String
  refs: [String!]
  relatedEntities: [RelatedEntity!]
  relatedOrderId: String
  relatedProduct: Product
  relatedProductId: String
  stockCode: String!
  type: ProductStockRecordType!
  updatedAt: Float
}

type ProductStockRecordPaginated {
  results: [ProductStockRecord!]!
  total: Float!
}

"""Product stock record type"""
enum ProductStockRecordType {
  STOCK_IN
  STOCK_OUT
}

type ProductStocksPaginated {
  results: [ProductStock!]!
  total: Float!
}

type ProductSupply {
  productId: String!
  quantity: Float!
}

input ProductSupplyInput {
  productId: String!
  quantity: Float!
}

"""Available product types"""
enum ProductType {
  COMBO
  PRODUCT
  SERVICE
  VOUCHER
}

type ProductVoucher {
  _id: String!
  amount: Float!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  customerId: String!
  expireAt: Float
  productVoucherId: String!
  ref: String!
  refs: [String!]
  relatedTicketId: String!
  status: ProductVoucherStatus!
  updatedAt: Float
}

"""Product voucher status"""
enum ProductVoucherStatus {
  ACTIVE
  EXPIRED
  INACTIVE
  OUT_OF_AMOUNT
}

type ProductVouchersPaginated {
  results: [ProductVoucher!]!
  total: Float!
}

type ProductsPaginated {
  results: [Product!]!
  total: Float!
}

type Promotion {
  _count: Float!
  _id: String
  createdAt: Float
  customFieldValues: [BaseCustomFieldValue!]
  customersSelection: JSONObject
  description: String
  expireAt: Float
  id: String!
  image: String
  limitPerCustomer: Float
  name: String!
  productsSelection: JSONObject
  refs: [String!]
  relatedEntities: [RelatedEntity!]
  status: PromotionStatus!
  type: PromotionType!
  updatedAt: Float
  value: Float!
}

"""Promotion status"""
enum PromotionStatus {
  ACTIVE
  CLOSED
  EXPIRED
}

"""Promotion type"""
enum PromotionType {
  DISCOUNT_AMOUNT
  DISCOUNT_RATE
}

type PromotionsPaginated {
  results: [Promotion!]!
  total: Float!
}

type Query {
  activities(contextId: String!, contextType: String!, ids: [String!], limit: Float = 30, offset: Float, parentId: String, sortCreatedAt: SortDirection, type: ActivityType): ActivitiesPaginated!
  activity(id: String!): Activity!
  appConfig: AppConfig!
  bookings(limit: Float = 30, offset: Float, query: JSONObject): BookingsPaginated!
  categories(limit: Float = 30, offset: Float, query: JSONObject): CategoriesPaginated!
  category(id: String!): Category!
  couponRules(limit: Float = 30, offset: Float, query: JSONObject): CouponRulesPaginated!
  coupons(limit: Float = 30, offset: Float, query: JSONObject): CouponsPaginated!
  customFields(limit: Float = 30, offset: Float, query: JSONObject): CustomFieldsPaginated!
  customer(id: String!): Customer!
  customerForms(limit: Float = 30, offset: Float, query: JSONObject): CustomerFormsPaginated!
  customers(ids: [String!], limit: Float = 30, offset: Float, sortCreatedAt: SortDirection): CustomersPaginated!
  eInvoices(limit: Float = 30, offset: Float, query: JSONObject): PluginEInvoicesPaginated!
  event(id: String!): Event!
  events(limit: Float = 30, offset: Float, ref: String, type: EventType, userId: String): EventsPaginated!
  files(limit: Float = 30, offset: Float, query: JSONObject): FilesPaginated!
  getCategoriesByIds(ids: [String!]!): [Category!]!
  getCategoryBySlug(slug: String!): Category!
  getFileInfo(fileId: String!): File!
  getProductByIds(ids: [String!]!): [Product!]!
  loan(id: String!): Loan!
  loans(customerCidNumber: String, customerId: String, limit: Float = 30, offset: Float, query: JSONObject, sortCreatedAt: SortDirection, status: [LoanStatus!]): LoansPaginated!
  orders(limit: Float = 30, offset: Float, query: JSONObject): OrdersPaginated!
  partners(limit: Float = 30, offset: Float, query: JSONObject): PartnersPaginated!
  pluginExternalStorage: PluginExternalStorage
  post(id: String!): Posts!
  posts(limit: Float = 30, offset: Float, query: JSONObject): PostsPaginated!
  prescriptions(limit: Float = 30, offset: Float, query: JSONObject): PrescriptionsPaginated!
  productCombos(limit: Float = 30, offset: Float, query: JSONObject): ProductCombosPaginated!
  productStockRecords(limit: Float = 30, offset: Float, query: JSONObject): ProductStockRecordPaginated!
  productStocks(limit: Float = 30, offset: Float, query: JSONObject): ProductStocksPaginated!
  productVouchers(limit: Float = 30, offset: Float, query: JSONObject): ProductVouchersPaginated!
  products(limit: Float = 30, offset: Float, query: JSONObject): ProductsPaginated!
  promotions(limit: Float = 30, offset: Float, query: JSONObject): PromotionsPaginated!
  reactions(entity: String!, entityId: String!, ids: [String!], limit: Float = 30, offset: Float, sortCreatedAt: SortDirection): ReactionsPaginated!
  reactionsCount(entity: String!, entityId: String!): ReactionsCount!
  receipts(limit: Float = 30, offset: Float, query: JSONObject): ReceiptsPaginated!
  search(entities: [String!]!, limit: Int, query: String!): [SearchResult!]!
  siblingTasks(_id: String!): SiblingTasks!
  tagBySlug(slug: String!): Tag!
  tags(ids: [String!], limit: Float = 30, offset: Float, sortCreatedAt: SortDirection, type: String): TagsPaginated!
  task(_id: String!): Task!
  taskByCode(code: String!): Task!
  taskMetrics(contextId: String, contextType: TaskContextType!): TaskMetrics!
  taskStatuses(contextId: String, contextType: TaskContextType, mode: GetTaskStatusesMode): ConfigTaskStatuses!
  tasks(all: Boolean, assigneeUserIds: [String!], folderId: String, fromTrackingTime: Float, ids: [String!], isClosedOnly: Boolean, isProgressOnly: Boolean, limit: Float = 30, offset: Float, parentId: String, partnerIds: [String!], priority: TaskPriority, sortCreatedAt: SortDirection, status: String, tagIds: [String!], toTrackingTime: Float): TasksPaginated!
  tasksCount(all: Boolean, assigneeUserIds: [String!], folderId: String, fromTrackingTime: Float, ids: [String!], isClosedOnly: Boolean, isProgressOnly: Boolean, limit: Float = 30, offset: Float, parentId: String, partnerIds: [String!], priority: TaskPriority, sortCreatedAt: SortDirection, status: String, tagIds: [String!], toTrackingTime: Float): Float!
  userWorkspaceMember: WorkspaceMember!
  userWorkspaceMembers: [WorkspaceMember!]!
  workspace: Workspace!
  workspaceApiApps(limit: Float = 30, offset: Float, query: JSONObject): WorkspaceApiAppsPaginated!
  workspaceBranches(limit: Float = 30, offset: Float, query: JSONObject): WorkspaceBranchesPaginated!
  workspaceInviteInformation(inviteCode: String!): WorkspaceInviteInformation!
  workspaceMember(userId: String!): WorkspaceMember!
  workspaceMembers(ids: [String!], ignoreSelf: Boolean, limit: Float = 30, offset: Float, query: JSONObject, sortCreatedAt: SortDirection, userId: [String!]): WorkspaceMembersPaginated!
  workspaceMembersByIds(ids: [String!]!): [WorkspaceMember!]!
  workspaceMembersOnlineStatus: [WorkspaceMemberOnlineStatus!]!
  workspaceRoles: [WorkspaceRole!]!
  workspaceStats(limit: Float = 30, offset: Float, query: JSONObject): WorkspaceStatsPaginated!
}

type Reaction {
  createdAt: Float!
  type: ReactionType!
  user: WorkspaceMember!
  userId: String!
}

type ReactionCount {
  count: Float!
  type: ReactionType!
  userIds: [String!]!
}

"""Available reaction types"""
enum ReactionType {
  ANGRY
  DISLIKE
  EYES
  LAUGH
  LIKE
  LOVE
  SAD
  SURPRISE
}

type ReactionsCount {
  reactions: [ReactionCount!]!
}

type ReactionsPaginated {
  results: [Reaction!]!
  total: Float!
}

type Receipt {
  _count: Float!
  _id: String
  amount: Float!
  assigneeUserIds: [String!]
  cashierUser: WorkspaceMember
  cashierUserId: String
  code: String!
  createdAt: Float
  customFieldValues: [BaseCustomFieldValue!]
  data: AnyType
  disbursementUser: WorkspaceMember
  disbursementUserId: String
  expireAt: Float
  giveAmount: AnyType
  id: String!
  note: String
  paidAt: Float
  paymentMethod: ReceiptPaymentMethod
  ref: String!
  refs: [String!]
  relatedCustomer: Customer
  relatedCustomerId: String
  relatedEntities: [RelatedEntity!]
  relatedLoanCode: String
  relatedLoanId: String
  relatedOrderId: String
  relatedPartnerId: String
  relatedTicketId: String
  status: ReceiptStatus!
  tipAmount: AnyType
  type: ReceiptType!
  updatedAt: Float
  workspaceBranch: WorkspaceBranch
}

"""Receipt payment method"""
enum ReceiptPaymentMethod {
  BANK_CARD
  BANK_TRANSFER
  CASH
}

"""Receipt status"""
enum ReceiptStatus {
  PAID
  PENDING
}

"""Receipt type"""
enum ReceiptType {
  EXPENSE
  INCOME
}

type ReceiptsPaginated {
  results: [Receipt!]!
  total: Float!
}

input RegisterDeviceDto {
  identifyId: String!
  locale: AppLocale
}

type RelatedEntity {
  data: JSONObject
  entity: String!
  id: String
  index: Boolean
}

interface SearchResult {
  entity: String!
  id: String!
}

type SearchResultCategory implements SearchResult {
  entity: String!
  id: String!
  name: String!
}

type SearchResultCustomer implements SearchResult {
  code: String!
  entity: String!
  id: String!
  name: String!
  phone: String
}

type SearchResultLoan implements SearchResult {
  code: String!
  customerName: String!
  customerPhone: String
  entity: String!
  id: String!
}

type SearchResultOrders implements SearchResult {
  code: String!
  entity: String!
  id: String!
}

type SearchResultPartner implements SearchResult {
  entity: String!
  id: String!
  name: String!
  phone: String
}

type SearchResultPrescriptions implements SearchResult {
  entity: String!
  id: String!
  name: String!
  note: String!
}

type SearchResultProduct implements SearchResult {
  entity: String!
  id: String!
  name: String!
}

type SearchResultReceipt implements SearchResult {
  code: String!
  entity: String!
  id: String!
}

type SearchResultTags implements SearchResult {
  entity: String!
  id: String!
  name: String!
  type: String!
}

type SearchResultTask implements SearchResult {
  code: String!
  entity: String!
  id: String!
  name: String!
}

type SearchResultWorkspaceMember implements SearchResult {
  avatar: String
  color: String
  email: String!
  entity: String!
  id: String!
  memberId: String
  name: String!
  phone: String
  userId: String!
}

type SiblingTasks {
  next: Task
  previous: Task
}

type SignUploadUrlResponse {
  dna: String!
  signedUrl: String!
}

"""Available sort directions"""
enum SortDirection {
  ASC
  DESC
}

type SyncTaskResult {
  task: Task!
  updateInfos: [String!]!
}

type Tag {
  _id: String!
  color: String
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  name: String!
  order: Float!
  refs: [String!]
  slug: String!
  type: TagType!
  updatedAt: Float
}

input TagDto {
  color: String
  name: String!
  order: Float
  type: TagType!
}

"""Available tag types"""
enum TagType {
  CUSTOMER
  MESSAGE_BOX
  TASK
  TASK_FOLDER
}

type TagsPaginated {
  results: [Tag!]!
  total: Float!
}

type Task {
  _id: String!
  assigneeUserIds: [String!]!
  assigneeUsers: [WorkspaceMember!]!
  childCount: Float!
  childDueDate: Float
  childEstimatedTime: Float
  childOrder: TaskChildOrder!
  childProgress: Float!
  childStartDate: Float
  childTimeline: TaskChildTimeline
  closedAt: Float
  code: String!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  customFields: [CustomField!]!
  customer: Customer
  customerId: String
  description: String
  dueDate: Float
  estimatedTime: Float
  folder: Tag
  folderId: String
  isArchived: Boolean
  mentionedUserIds: [String!]!
  name: String!
  order: Float!
  parent: Task
  parentId: String
  partnerIds: [String!]!
  partners: [Partner!]!
  points: Float
  priority: TaskPriority
  progress: Float!
  refs: [String!]
  relatedUserIds: [String!]!
  startDate: Float
  status: String!
  statuses: [TaskStatus!]!
  tagIds: [String!]!
  tags: [Tag!]!
  timeTrackings: [TaskTimeTracking!]
  updatedAt: Float
}

type TaskChildOrder {
  first: Float
  last: Float
}

type TaskChildTimeline {
  dueDate: Float
  startDate: Float
}

"""Available task statuses context types"""
enum TaskContextType {
  FOLDER
}

type TaskMetrics {
  contextId: String
  contextType: TaskContextType!
  dueDate: Float
  estimatedTime: Float
  inProgressTasks: Float
  overdueTasks: Float
  progress: Float
  startDate: Float
  totalTasks: Float
}

"""Available task priorities"""
enum TaskPriority {
  HIGH
  LOW
  MEDIUM
  URGENT
}

type TaskStatus {
  color: String
  contextId: String
  contextType: TaskContextType
  id: String!
  name: String
  order: Float!
  progress: Float!
}

input TaskStatusInput {
  color: String
  id: String!
  name: String
  order: Float
}

type TaskTimeTracking {
  endAt: Float
  id: String!
  note: String
  startAt: Float!
  user: WorkspaceMember
  userId: String!
  workspaceId: String!
}

input TaskTimeTrackingInput {
  endAt: Float
  id: String!
  note: String
  startAt: Float!
  userId: String!
}

type TasksPaginated {
  results: [Task!]!
  total: Float!
}

input UpdateTagInput {
  _id: String!
  color: String
  name: String
  order: Float
}

input UpdateTaskInput {
  _id: String!
  assigneeUserIds: [String!]
  customerId: String
  description: String
  dueDate: Float
  estimatedTime: Float
  folderId: String
  isArchived: Boolean
  name: String
  order: Float
  parentId: String
  partnerIds: [String!]
  points: Float
  priority: TaskPriority
  startDate: Float
  status: String
  tagIds: [String!]
  timeTrackings: [TaskTimeTrackingInput!]
  workspaceBranchId: String
}

type UserAuthProvider {
  providerId: String!
  uid: String!
  username: String!
}

type Workspace {
  _id: String!
  appColor: String
  appColorShape: Float
  appDomain: String
  appIcon: String
  appName: String
  branches: Float!
  code: String!
  hotline: String
  inviteCode: String
  isArchived: Boolean
  locale: AppLocale
  location: LocationEntity
  logo: String
  name: String!
  phone: String
  type: WorkspaceType!
}

type WorkspaceApiApp {
  _id: String!
  authVersion: Float!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  enabled: Boolean!
  member: WorkspaceMember!
  memberId: String!
  refs: [String!]
  secretKey: String!
  updatedAt: Float
  userId: String!
}

type WorkspaceApiAppsPaginated {
  results: [WorkspaceApiApp!]!
  total: Float!
}

type WorkspaceBranch {
  _id: String!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  hotline: String
  location: LocationEntity!
  name: String!
  refs: [String!]
  updatedAt: Float
}

type WorkspaceBranchesPaginated {
  results: [WorkspaceBranch!]!
  total: Float!
}

type WorkspaceInviteInformation {
  appColor: String
  appColorShape: Float
  hotline: String
  logo: String
  name: String!
  phone: String
  type: WorkspaceType!
  workspaceId: String!
}

type WorkspaceMember {
  _id: String!
  avatar: String
  color: String
  email: String!
  joinedAt: Float
  memberDisplayName: String
  memberId: String
  name: String!
  permissions: [String!]!
  phone: String
  roles: [WorkspaceMemberRole!]!
  userDisplayName: String
  userId: String!
  workingTimeType: WorkspaceMemberWorkingTimeType
  workspace: Workspace!
  workspaceBranches: [WorkspaceMemberWorkspaceBranchInfo!]!
  workspaceId: String!
}

type WorkspaceMemberOnlineStatus {
  isOnline: Boolean!
  userId: String!
}

type WorkspaceMemberRole {
  _id: String!
  color: String
  name: String!
}

"""The working time type of the workspace member"""
enum WorkspaceMemberWorkingTimeType {
  FREELANCER
  FULLTIME
}

type WorkspaceMemberWorkspaceBranchInfo {
  _id: String!
  name: String!
}

type WorkspaceMembersPaginated {
  results: [WorkspaceMember!]!
  total: Float!
}

type WorkspaceRole {
  _id: String!
  color: String
  description: String
  isEditable: Boolean!
  name: String!
  permissions: [String!]!
}

type WorkspaceStat {
  _id: String!
  bookingCount: Float
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  customerCount: Float
  memberCount: Float
  orderCount: Float
  refs: [String!]
  storageUsage: Float
  updatedAt: Float
  workspace: WorkspaceStatWorkspaceInformation!
}

type WorkspaceStatWorkspaceInformation {
  _id: String!
  logo: String
  name: String!
  type: WorkspaceType!
}

type WorkspaceStatsPaginated {
  results: [WorkspaceStat!]!
  total: Float!
}

"""Available workspace types"""
enum WorkspaceType {
  BEAUTY_SALON
  BUSINESS
  CLINIC
  CREDIT
  DENTAL
  HOSPITAL
  SOFTWARE
  SPA
}