"""The `AnyType` scalar type represents any value without restrictions."""
scalar AnyType

type AppConfig {
  UTC: String!
  firebase: FirebaseClientConfig!
  metaAppId: String!
  metaAppScope: [String!]!
  metaAppVersion: String!
  name: String!
  timeZone: String!
  version: String!
  workspaceDomainIP: String!
  zaloAppId: String!
}

"""Available locales"""
enum AppLocale {
  EN
  VI
}

type CategoriesPaginated {
  count: Float!
  data: [Category!]!
}

type Category {
  _id: String!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  customFields: [CustomField!]
  description: String
  icon: String
  name: String!
  order: Float!
  parentId: String
  refs: [String!]
  relatedEntities: [RelatedEntity!]
  slug: String!
  thumbnail: String
  type: CategoryType!
  updatedAt: Float
}

type CategoryEntity {
  _id: String!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  description: String
  icon: String
  name: String!
  order: Float!
  parentId: String
  refs: [String!]
  relatedEntities: [RelatedEntity!]
  slug: String!
  thumbnail: String
  type: CategoryType!
  updatedAt: Float
}

"""Available category types"""
enum CategoryType {
  COMMON
  POSTS
  PRODUCTS
}

type CustomField {
  config: JSONObject
  customFieldId: String!
  key: String
  type: CustomFieldType!
  value: AnyType
}

"""Available custom field types"""
enum CustomFieldType {
  DATE
  FILE
  MULTI_SELECT
  NUMBER
  SELECT
  SWITCH
  TEXT
  TEXTAREA
}

type CustomFieldValue {
  customFieldId: String!
  value: AnyType
}

input CustomFieldValueInput {
  customFieldId: String!
  value: AnyType
}

type DeviceEntity {
  _id: String!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  identifyId: String
  lastActiveAt: Float!
  locale: AppLocale
  notificationToken: String
  refs: [String!]
  relatedEntities: [RelatedEntity!]
  updatedAt: Float
  userAgent: String!
  userId: String
}

type File {
  _id: String!
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  externalUrl: String
  fileName: String!
  path: String!
  ref: String
  refs: [String!]
  relatedCustomerId: String
  relatedEntities: [RelatedEntity!]
  relatedHrmTimekeepingId: String
  relatedMessageBoxId: String
  relatedMessageId: String
  relatedProductId: String
  relatedReceiptId: String
  relativePath: String
  size: Float
  thumbnail: String
  type: FileType!
  updatedAt: Float
  uploadByUserId: String
  url: String!
  workspaceId: String!
}

"""Available file types"""
enum FileType {
  AUDIO
  MS_EXCEL
  MS_POWERPOINT
  MS_WORD
  PDF
  PHOTO
  UNKNOWN
  VIDEO
}

type FirebaseClientConfig {
  apiKey: String!
  appId: String!
  authDomain: String!
  measurementId: String!
  messagingSenderId: String!
  projectId: String!
  storageBucket: String!
}

"""
The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSONObject

type Mutation {
  createCategory(customFieldValues: [CustomFieldValueInput!], description: String, icon: String, name: String!, order: Float, parentId: String, slug: String, thumbnail: String, type: CategoryType): Category!
  createProduct(categoryId: String, code: String, combos: [ProductComboInput!], combosExpireInDays: Float, content: String, customFieldValues: [CustomFieldValueInput!], defaultQtyPerUse: Float, displayName: String, image: String, isHiddenInReceiptWhenNoPrice: Boolean, isStockCheck: Boolean, maxPrice: Float, minPrice: Float, name: String!, price: Float!, productCode: String, supplies: [ProductSupplyInput!], tags: [String!], type: ProductType!, unit: String!, voucherAmount: Float, voucherExcludeProductIds: [String!], voucherExpireInDays: Float, voucherIncludeProductIds: [String!], warningOutOfDateBeforeDays: Float, warningOutOfStockQty: Float): Product!
  deleteCategory(id: String!): Boolean!
  externalStorageVerifyDna(dna: String!): File!
  generateCategorySlug(name: String!): String!
  healthcheckPluginExternalStorage: Boolean!
  interactCategory(id: String!): Boolean!
  pluginExternalStorageSignUploadUrl(fileName: String!, refs: [String!]): SignUploadUrlResponse!
  registerDevice(input: RegisterDeviceDto!): DeviceEntity!
  removePluginExternalStorage: Boolean!
  setPluginExternalStorage(accessKeyId: String, bucketName: String, endpointUrl: String, provider: PluginExternalStorageProvider!, region: String, secretAccessKey: String): PluginExternalStorage!
  toggleDisablePluginExternalStorage: Boolean!
  updateCategory(customFieldValues: [CustomFieldValueInput!], description: String, icon: String, id: String!, name: String!, order: Float, parentId: String, slug: String, thumbnail: String, type: CategoryType): Category!
}

type PluginExternalStorage {
  bucketName: String
  endpointUrl: String
  isDisabled: Boolean
  provider: PluginExternalStorageProvider!
  region: String
}

"""Available external storage providers"""
enum PluginExternalStorageProvider {
  AWS_S3
}

type Product {
  _id: String!
  category: CategoryEntity
  categoryId: String
  code: String
  combos: [ProductCombo!]
  combosExpireInDays: Float
  content: String
  createdAt: Float
  customFieldValues: [CustomFieldValue!]
  defaultQtyPerUse: Float
  displayName: String
  image: String
  inStock: Float
  isHiddenInReceiptWhenNoPrice: Boolean
  isStockCheck: Boolean
  maxPrice: Float
  minPrice: Float
  name: String!
  price: Float!
  productCode: String
  refs: [String!]
  relatedEntities: [RelatedEntity!]
  supplies: [ProductSupply!]
  tags: [String!]!
  type: ProductType!
  unit: String!
  updatedAt: Float
  voucherAmount: Float
  voucherExcludeProductIds: [String!]
  voucherExpireInDays: Float
  voucherIncludeProductIds: [String!]
  warningOutOfDateBeforeDays: Float
  warningOutOfStockQty: Float
  workspaceId: String!
}

type ProductCombo {
  productId: String!
  quantity: Float!
}

input ProductComboInput {
  productId: String!
  quantity: Float!
}

type ProductSupply {
  productId: String!
  quantity: Float!
}

input ProductSupplyInput {
  productId: String!
  quantity: Float!
}

"""Available product types"""
enum ProductType {
  COMBO
  PRODUCT
  SERVICE
  VOUCHER
}

type Query {
  appConfig: AppConfig!
  categoriesPaginated(limit: Float = 20, offset: Float = 0, query: JSONObject): CategoriesPaginated!
  getCategoriesByIds(ids: [String!]!): [Category!]!
  getCategory(id: String!): Category!
  getCategoryBySlug(slug: String!): Category!
  getFileInfo(fileId: String!): File!
  getProductByIds(ids: [String!]!): [Product!]!
  pluginExternalStorage: PluginExternalStorage
}

input RegisterDeviceDto {
  identifyId: String!
  locale: AppLocale
}

type RelatedEntity {
  data: JSONObject
  entity: String!
  id: String
  index: Boolean
}

type SignUploadUrlResponse {
  dna: String!
  signedUrl: String!
}

type UserAuthProvider {
  providerId: String!
  uid: String!
  username: String!
}