fragment TaskData on Task {
  _id
  code
  name
  description
  status
  order

  folderId
  childCount
  childOrders

  startDate
  dueDate
  estimatedTime

  priority
  progress
  childProgress

  partners {
    _id
    name
    logo
  }

  assigneeUsers {
    _id
    userId
    name
    color
    avatar
    roles {
      _id
      name
      color
    }
  }

  customer {
    _id
    name
    avatar
    phone
  }

  parentId
  parent {
    _id
    name
    code
    order
    folderId

    folder {
      _id
      color
      name
    }
  }

  tags {
    _id
    color
    name
  }

  folder {
    _id
    color
    name
  }

  timeTrackings {
    id
    workspaceId
    userId
    user {
      _id
      name
      color
      avatar
    }
    billable
    note
    startAt
    endAt
  }

  createdAt
  isArchived
}
