import type * as Types from '../../../graphql/types.graphql.d';

export type TaskByIdQueryVariables = Types.Exact<{
  id: Types.Scalars['String']['input'];
}>;


export type TaskByIdQuery = { __typename: 'Query', task: { __typename: 'Task', _id: string, code: string, name: string, description: string | null, status: string, order: number, folderId: string | null, childCount: number, childOrders: Array<number> | null, startDate: number | null, dueDate: number | null, estimatedTime: number | null, priority: Types.TaskPriority | null, progress: number | null, childProgress: number | null, parentId: string | null, createdAt: number | null, isArchived: boolean | null, partners: Array<{ __typename: 'PartnerEntity', _id: string, name: string, logo: string | null }>, assigneeUsers: Array<{ __typename: 'WorkspaceMemberInfo', _id: string, userId: string, name: string, color: string | null, avatar: string | null, roles: Array<{ __typename: 'WorkspaceMemberRole', _id: string, name: string, color: string | null }> }>, customer: { __typename: 'CustomerEntity', _id: string, name: string, avatar: string | null, phone: string | null } | null, parent: { __typename: 'Task', _id: string, name: string, code: string, order: number, folderId: string | null, folder: { __typename: 'TagEntity', _id: string, color: string | null, name: string } | null } | null, tags: Array<{ __typename: 'TagEntity', _id: string, color: string | null, name: string }>, folder: { __typename: 'TagEntity', _id: string, color: string | null, name: string } | null, timeTrackings: Array<{ __typename: 'TaskTimeTracking', id: string, workspaceId: string, userId: string, billable: boolean, note: string | null, startAt: number, endAt: number | null, user: { __typename: 'WorkspaceMemberInfo', _id: string, name: string, color: string | null, avatar: string | null } | null }> | null } };

declare const Document: import("graphql").DocumentNode; export default Document;