import { registerEnumType } from '@nestjs/graphql';
import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsBoolean,
  IsEnum,
  IsNumber,
  IsObject,
  IsOptional,
  IsString,
  ValidateNested,
} from 'class-validator';
import { RelatedEntity } from '../database/database.entities';
import { type NotificationsService } from '../notifications/notifications.service';
import { type QueueProducersService } from '../queue-producers/queue-producers.service';
import { ReportTimeSeriesInput } from '../reports/reports.types';
import { EventEntity } from './events.entity';
import type { WorkspaceMembersService } from '../workspace-members/workspace-members.service';
import { TasksService } from '../tasks/tasks.service';
import { LoansService } from '../loans/loans.service';
import { PluginMailerService } from '../plugin-mailer/plugin-mailer.service';
import { WorkspacesService } from '../workspaces/workspaces.service';
import { MessageBoxesService } from 'src/message-boxes/message-boxes.service';

export enum EventVariant {
  INFO = 'INFO',
  WARNING = 'WARNING',
  NEGATIVE = 'NEGATIVE',
  POSITIVE = 'POSITIVE',
}

registerEnumType(EventVariant, {
  name: 'EventVariant',
  description: 'Available event variants',
});

export enum EventType {
  CUSTOM_FIELDS_NEW = 'CUSTOM_FIELDS_NEW',
  CUSTOM_FIELDS_UPDATED = 'CUSTOM_FIELDS_UPDATED',
  CUSTOM_FIELDS_REMOVED = 'CUSTOM_FIELDS_REMOVED',

  WORKSPACE_NEW = 'WORKSPACE_NEW',
  WORKSPACE_UPDATED = 'WORKSPACE_UPDATED',
  WORKSPACE_ARCHIVED = 'WORKSPACE_ARCHIVED',
  WORKSPACE_INVITE_CODE_UPDATED = 'WORKSPACE_INVITE_CODE_UPDATED',
  WORKSPACE_STATS_UPDATED = 'WORKSPACE_STATS_UPDATED',
  WORKSPACE_SETTING_UPDATED = 'WORKSPACE_SETTING_UPDATED',

  WORKSPACE_BRANCH_NEW = 'WORKSPACE_BRANCH_NEW',
  WORKSPACE_BRANCH_UPDATED = 'WORKSPACE_BRANCH_UPDATED',
  WORKSPACE_BRANCH_ARCHIVED = 'WORKSPACE_BRANCH_ARCHIVED',

  WORKSPACE_ROLES_NEW = 'WORKSPACE_ROLES_NEW',
  WORKSPACE_ROLES_UPDATED = 'WORKSPACE_ROLES_UPDATED',
  WORKSPACE_ROLES_REMOVED = 'WORKSPACE_ROLES_REMOVED',

  WORKSPACE_BILLINGS_DEPOSITED = 'WORKSPACE_BILLINGS_DEPOSITED',
  WORKSPACE_BILLINGS_WITHDRAWN = 'WORKSPACE_BILLINGS_WITHDRAWN',
  WORKSPACE_BILLINGS_PAYMENT_NEW = 'WORKSPACE_BILLINGS_PAYMENT_NEW',
  WORKSPACE_BILLINGS_CASHBACK_NEW = 'WORKSPACE_BILLINGS_CASHBACK_NEW',
  WORKSPACE_BILLINGS_PAYMENT_PAID = 'WORKSPACE_BILLINGS_PAYMENT_PAID',

  WORKSPACE_API_APP_CREATED = 'WORKSPACE_API_APP_CREATED',
  WORKSPACE_API_APP_UPDATED = 'WORKSPACE_API_APP_UPDATED',
  WORKSPACE_API_APP_ARCHIVED = 'WORKSPACE_API_APP_ARCHIVED',

  WORKSPACE_SUBSCRIPTION_UPDATED = 'WORKSPACE_SUBSCRIPTION_UPDATED',

  WORKSPACE_MEMBER_JOINED = 'WORKSPACE_MEMBER_JOINED',
  WORKSPACE_MEMBER_LEAVED = 'WORKSPACE_MEMBER_LEAVED',
  WORKSPACE_MEMBER_UPDATED = 'WORKSPACE_MEMBER_UPDATED',
  WORKSPACE_MEMBER_ASSIGN_ROLES = 'WORKSPACE_MEMBER_ASSIGN_ROLES',
  WORKSPACE_MEMBER_SYNCED = 'WORKSPACE_MEMBER_SYNCED',
  WORKSPACE_MEMBER_TRANSFER_OWNER = 'WORKSPACE_MEMBER_TRANSFER_OWNER',
  WORKSPACE_MEMBER_ONLINE = 'WORKSPACE_MEMBER_ONLINE',
  WORKSPACE_MEMBER_OFFLINE = 'WORKSPACE_MEMBER_OFFLINE',

  CUSTOMER_NEW = 'CUSTOMER_NEW',
  CUSTOMER_UPDATED = 'CUSTOMER_UPDATED',
  CUSTOMER_ASSIGN_TO_USER = 'CUSTOMER_ASSIGN_TO_USER',
  CUSTOMER_UNASSIGN_USER = 'CUSTOMER_UNASSIGN_USER',
  CUSTOMER_CONTACTS_UPDATED = 'CUSTOMER_CONTACTS_UPDATED',
  CUSTOMER_ARCHIVED = 'CUSTOMER_ARCHIVED',
  CUSTOMER_BULK_UPDATE_WORKSPACE_BRANCH = 'CUSTOMER_BULK_UPDATE_WORKSPACE_BRANCH',

  CUSTOMER_FORM_NEW = 'CUSTOMER_FORM_NEW',
  CUSTOMER_FORM_UPDATED = 'CUSTOMER_FORM_UPDATED',
  CUSTOMER_FORM_ARCHIVED = 'CUSTOMER_FORM_ARCHIVED',

  BOOKING_NEW = 'BOOKING_NEW',
  BOOKING_UPDATED = 'BOOKING_UPDATED',
  BOOKING_CHECKIN = 'BOOKING_CHECKIN',
  BOOKING_IN_PROGRESS = 'BOOKING_IN_PROGRESS',
  BOOKING_COMPLETED = 'BOOKING_COMPLETED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',

  COMMENT_NEW = 'COMMENT_NEW',
  COMMENT_UPDATED = 'COMMENT_UPDATED',
  COMMENT_REMOVED = 'COMMENT_REMOVED',
  COMMENT_PINNED = 'COMMENT_PINNED',
  COMMENT_UNPINNED = 'COMMENT_UNPINNED',

  TAGS_ARCHIVED = 'TAGS_ARCHIVED',
  TAGS_UPDATED = 'TAGS_UPDATED',
  TAG_NEW = 'TAG_NEW',

  PRODUCT_NEW = 'PRODUCT_NEW',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_ARCHIVED = 'PRODUCT_ARCHIVED',

  REPORT_TIME_SERIES_SYNCED = 'REPORT_TIME_SERIES_SYNCED',
  REPORT_METRICS_SYNCED = 'REPORT_METRICS_SYNCED',

  PRODUCT_STOCK_IN = 'PRODUCT_STOCK_IN',
  PRODUCT_STOCK_IN_REVERT = 'PRODUCT_STOCK_IN_REVERT',
  PRODUCT_STOCK_OUT = 'PRODUCT_STOCK_OUT',
  PRODUCT_STOCK_OUT_REVERT = 'PRODUCT_STOCK_OUT_REVERT',
  PRODUCT_STOCK_IN_MULTIPLE = 'PRODUCT_STOCK_IN_MULTIPLE',

  PRODUCT_VOUCHERS_NEW = 'PRODUCT_VOUCHERS_NEW',

  PRODUCT_COMBO_NEW = 'PRODUCT_COMBO_NEW',
  PRODUCT_COMBO_UPDATE = 'PRODUCT_COMBO_UPDATE',

  NOTIFICATION_NEW = 'NOTIFICATION_NEW',
  NOTIFICATION_READED = 'NOTIFICATION_READED',
  NOTIFICATION_LIST_VIEWED = 'NOTIFICATION_LIST_VIEWED',
  NOTIFICATION_CLEANED = 'NOTIFICATION_CLEANED',

  PARTNER_NEW = 'PARTNER_NEW',
  PARTNER_UPDATED = 'PARTNER_UPDATED',
  PARTNER_ARCHIVED = 'PARTNER_ARCHIVED',

  TASK_NEW = 'TASK_NEW',
  TASK_NAME_UPDATED = 'TASK_NAME_UPDATED',
  TASK_DESCRIPTION_UPDATED = 'TASK_DESCRIPTION_UPDATED',
  TASK_PRIORITY_UPDATED = 'TASK_PRIORITY_UPDATED',
  TASK_STATUS_UPDATED = 'TASK_STATUS_UPDATED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_ARCHIVED = 'TASK_ARCHIVED',
  TASKS_UPDATED = 'TASKS_UPDATED',
  TASK_SYNCED = 'TASK_SYNCED',
  TASK_METRIC_SYNCED = 'TASK_METRIC_SYNCED',

  FILE_NEW = 'FILE_NEW',
  FILE_REMOVED = 'FILE_REMOVED',

  RECEIPT_NEW = 'RECEIPT_NEW',
  RECEIPT_PAID = 'RECEIPT_PAID',
  RECEIPT_UPDATED = 'RECEIPT_UPDATED',
  RECEIPT_DISBURSEMENT = 'RECEIPT_DISBURSEMENT',
  RECEIPT_ARCHIVED = 'RECEIPT_ARCHIVED',
  RECEIPT_UNARCHIVED = 'RECEIPT_UNARCHIVED',
  RECEIPT_SYNCED = 'RECEIPT_SYNCED',
  RECEIPT_CHANGE_WORKSPACE_BRANCH = 'RECEIPT_CHANGE_WORKSPACE_BRANCH',
  RECEIPT_REVERT_PAYMENT = 'RECEIPT_REVERT_PAYMENT',

  PRODUCT_SUPPLY_RECORD_NEW = 'PRODUCT_SUPPLY_RECORD_NEW',

  PLUGIN_ZALO_OA_ACTIVE = 'PLUGIN_ZALO_OA_ACTIVE',
  PLUGIN_ZALO_OA_INACTIVE = 'PLUGIN_ZALO_OA_INACTIVE',
  PLUGIN_ZALO_OA_UPDATED = 'PLUGIN_ZALO_OA_UPDATED',
  PLUGIN_ZALO_OA_REMOVED = 'PLUGIN_ZALO_OA_REMOVED',
  PLUGIN_ZALO_OA_ENABLED = 'PLUGIN_ZALO_OA_ENABLED',
  PLUGIN_ZALO_OA_DISABLED = 'PLUGIN_ZALO_OA_DISABLED',

  PLUGIN_META_PAGES_UPDATED = 'PLUGIN_META_PAGES_UPDATED',
  PLUGIN_META_PAGES_DISCONNECTED = 'PLUGIN_META_PAGES_DISCONNECTED',

  PRESCRIPTIONS_NEW = 'PRESCRIPTIONS_NEW',
  PRESCRIPTIONS_UPDATED = 'PRESCRIPTIONS_UPDATED',
  PRESCRIPTIONS_REMOVED = 'PRESCRIPTIONS_REMOVED',

  MESSAGE_BOX_NEW = 'MESSAGE_BOX_NEW',
  MESSAGE_BOX_WAITING = 'MESSAGE_BOX_WAITING',
  MESSAGE_BOX_NEW_MESSAGE = 'MESSAGE_BOX_NEW_MESSAGE',
  MESSAGE_BOX_IN_PROGRESS = 'MESSAGE_BOX_IN_PROGRESS',
  MESSAGE_BOX_REMOVED = 'MESSAGE_BOX_REMOVED',
  MESSAGE_BOX_CLOSED = 'MESSAGE_BOX_CLOSED',
  MESSAGE_BOX_UPDATED = 'MESSAGE_BOX_UPDATED',
  MESSAGE_BOXES_PLATFORMS_UPDATED = 'MESSAGE_BOXES_PLATFORMS_UPDATED',

  MESSAGE_NEW = 'MESSAGE_NEW',
  MESSAGE_UPDATED = 'MESSAGE_UPDATED',

  TABLE_SLOT_NEW = 'TABLE_SLOT_NEW',
  TABLE_SLOT_UPDATED = 'TABLE_SLOT_UPDATED',
  TABLE_SLOT_ARCHIVED = 'TABLE_SLOT_ARCHIVED',

  BANK_TRANSACTION_PAID = 'BANK_TRANSACTION_PAID',
  BANK_TRANSACTION_FULFILLED = 'BANK_TRANSACTION_FULFILLED',
  BANK_TRANSACTION_CANCELLED = 'BANK_TRANSACTION_CANCELLED',
  BANK_TRANSACTION_FAILED = 'BANK_TRANSACTION_FAILED',

  CUSTOMER_KYC_PENDING = 'CUSTOMER_KYC_PENDING',
  CUSTOMER_KYC_APPROVED = 'CUSTOMER_KYC_APPROVED',
  CUSTOMER_KYC_REJECTED = 'CUSTOMER_KYC_REJECTED',

  LOANS_JUST_CREATED = 'LOANS_JUST_CREATED',
  LOANS_PENDING = 'LOANS_PENDING',
  LOANS_APPROVED = 'LOANS_APPROVED',
  LOANS_APPROVED_REVERTED = 'LOANS_APPROVED_REVERTED',
  LOANS_FULFILLED_REVERTED = 'LOANS_FULFILLED_REVERTED',
  LOANS_REJECTED = 'LOANS_REJECTED',
  LOANS_REVERT_REJECTED = 'LOANS_REVERT_REJECTED',
  LOANS_UPDATED = 'LOANS_UPDATED',
  LOANS_SYNCED = 'LOANS_SYNCED',
  LOANS_FULFILLED = 'LOANS_FULFILLED',
  LOANS_COMPLETED = 'LOANS_COMPLETED',
  LOANS_ARCHIVED = 'LOANS_ARCHIVED',
  LOANS_LIQUIDATION = 'LOANS_LIQUIDATION',
  LOANS_REVERT_LIQUIDATION = 'LOANS_REVERT_LIQUIDATION',
  LOANS_CHANGE_WORKSPACE_BRANCH = 'LOANS_CHANGE_WORKSPACE_BRANCH',

  PLUGIN_MESSAGE_HUBS_NEW = 'PLUGIN_MESSAGE_HUBS_NEW',
  PLUGIN_MESSAGE_HUBS_UPDATED = 'PLUGIN_MESSAGE_HUBS_UPDATED',
  PLUGIN_MESSAGE_HUBS_REMOVED = 'PLUGIN_MESSAGE_HUBS_REMOVED',

  PLUGIN_AI_ASSISTANTS_NEW = 'PLUGIN_AI_ASSISTANTS_NEW',
  PLUGIN_AI_ASSISTANTS_UPDATED = 'PLUGIN_AI_ASSISTANTS_UPDATED',
  PLUGIN_AI_ASSISTANTS_REMOVED = 'PLUGIN_AI_ASSISTANTS_REMOVED',

  USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
  USER_ONLINE = 'USER_ONLINE',
  USER_OFFLINE = 'USER_OFFLINE',

  ORDER_NEW = 'ORDER_NEW',
  ORDER_UPDATED = 'ORDER_UPDATED',
  ORDER_ARCHIVED = 'ORDER_ARCHIVED',
  ORDER_SYNCED = 'ORDER_SYNCED',

  POST_NEW = 'POST_NEW',
  POST_UPDATED = 'POST_UPDATED',
  POST_ARCHIVED = 'POST_ARCHIVED',

  CATEGORY_NEW = 'CATEGORY_NEW',
  CATEGORY_UPDATED = 'CATEGORY_UPDATED',
  CATEGORY_ARCHIVED = 'CATEGORY_ARCHIVED',

  PROMOTION_NEW = 'PROMOTION_NEW',
  PROMOTION_UPDATED = 'PROMOTION_UPDATED',
  PROMOTION_ARCHIVED = 'PROMOTION_ARCHIVED',

  E_INVOICE_CREATED = 'E_INVOICE_CREATED',
  E_INVOICE_REMOVED = 'E_INVOICE_REMOVED',

  ACTIVITY_NEW = 'ACTIVITY_NEW',
  ACTIVITY_UPDATED = 'ACTIVITY_UPDATED',
  ACTIVITY_ARCHIVED = 'ACTIVITY_ARCHIVED',
  ACTIVITY_SYNCED = 'ACTIVITY_SYNCED',

  REACTION_ADDED = 'REACTION_ADDED',
  REACTION_REMOVED = 'REACTION_REMOVED',

  ATTENDANCE_RECORD_NEW = 'ATTENDANCE_RECORD_NEW',
  ATTENDANCE_RECORD_APPROVED = 'ATTENDANCE_RECORD_APPROVED',
  ATTENDANCE_RECORD_REJECTED = 'ATTENDANCE_RECORD_REJECTED',
  ATTENDANCE_SETTING_UPDATED = 'ATTENDANCE_SETTING_UPDATED',

  FILE_EXPORT_NEW = 'FILE_EXPORT_NEW',
  FILE_EXPORT_FINISHED = 'FILE_EXPORT_FINISHED',
  FILE_EXPORT_FAILED = 'FILE_EXPORT_FAILED',
}

registerEnumType(EventType, {
  name: 'EventType',
  description: 'Available event types',
});

export enum EventDataActionType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  ARCHIVED = 'ARCHIVED',
}

registerEnumType(EventDataActionType, {
  name: 'EventDataActionType',
  description: 'Available event data action types',
});

registerEnumType(EventDataActionType, {
  name: 'EventDataActionType',
  description: 'Available event data action types',
});

export enum EventChannel {
  WORKSPACE = 'WORKSPACE',
  PERSONAL = 'PERSONAL',
  NONE = 'NONE',
}

registerEnumType(EventChannel, {
  name: 'EventChannel',
  description: 'Available event channels',
});

export class CaptureEventInput {
  @ApiProperty()
  @IsString()
  @IsOptional()
  workspaceId?: string;

  @ApiProperty()
  @IsString()
  @IsOptional()
  sessionId?: string;

  @ApiProperty()
  @IsEnum(EventChannel)
  @IsOptional()
  channel?: EventChannel;

  @ApiProperty()
  @IsEnum(EventType)
  type: EventType;

  @ApiProperty()
  @IsOptional()
  @IsEnum(EventDataActionType)
  actionType?: EventDataActionType;

  @ApiProperty()
  @IsOptional()
  @IsEnum(EventVariant)
  variant?: EventVariant;

  @ApiProperty()
  @IsString()
  @IsOptional()
  userId?: string;

  @ApiProperty()
  @IsString()
  @IsOptional()
  ref?: string;

  @ApiProperty()
  @IsObject()
  @IsOptional()
  data?: any;

  @ApiProperty()
  @IsBoolean()
  @IsOptional()
  persist?: boolean;

  @ApiProperty()
  @IsNumber()
  @IsOptional()
  time?: number;

  @ApiProperty()
  @IsObject()
  @IsOptional()
  relatedEntities?: RelatedEntity[];

  @ApiProperty()
  @Type(() => ReportTimeSeriesInput)
  @ValidateNested()
  @IsOptional()
  reportTimeRange?: ReportTimeSeriesInput;
}

export interface SocketAuthInput {
  token: string;
  deviceId: string;
}

export interface SocketJoinWorkspaceInput {
  workspaceId: string;
  token: string;
  deviceId: string;
}

export interface SocketListenUsersInput {
  addUserIds?: string[];
  removeUserIds?: string[];
}

export interface SendUserEventInput {
  userId: string;
  eventName: string;
  data?: any;
}

// ======================= SDK Related =======================
export interface SdkSocketJoinDto {
  key: string;
}
export interface SdkSendEventDto {
  workspaceId: string;
  type: EventType;
  data: EventEntity;
}

export interface EventHandlerContext {
  event: EventEntity;
  eventTitle: string;
  notifications: NotificationsService;
  queueProducers: QueueProducersService;
  workspaces: WorkspacesService;
  workspaceMembers: WorkspaceMembersService;
  tasks: TasksService;
  loans: LoansService;
  mailer: PluginMailerService;
  messageBoxes: MessageBoxesService;
}

export type EventHandler = (context: EventHandlerContext) => Promise<void>;
export type EventsHandler = Partial<Record<EventType, EventHandler[]>>;
