fragment Product on Product {
  _id
  name
  displayName
  image
  type
  tags
  code
  productCode
  content
  defaultQtyPerUse
  voucherExpireInDays
  warningOutOfDateBeforeDays
  warningOutOfStockQty
  categoryId
  category {
    _id
    name
    type
  }
  stock {
    quantity
  }
  unit
  price
  maxPrice
  minPrice
  combos {
    quantity
    productId
    product {
      _id
      name
    }
  }
  combosExpireInDays
  supplies {
    productId
    quantity
    product {
      _id
      name
      unit
    }
  }
  voucherIncludeProducts {
    _id
    name
  }
  voucherExcludeProducts {
    _id
    name
  }
  isStockCheck
  voucherAmount
  isHiddenInReceiptWhenNoPrice
  customFieldValues {
    type
    key
    config
    customFieldId
    value
  }
}
