#import "../../locations/graphql/fragmentLocation.graphql"
#import "../../workspace-members/graphql/fragmentWorkspaceMember.graphql"
#import "../../workspace-branches/graphql/fragmentWorkspaceBranch.graphql"

fragment Customer on Customer {
  _id
  refs
  createdAt
  updatedAt
  code
  codePrefix
  plainCode
  name
  birthday
  birthdayDate
  birthdayMonth
  phone
  avatar
  email
  presenterCustomerId
  gender
  medicalHistory
  assigneeUserIds
  tagIds
  salaryAmount
  relatedCustomerIds
  lastCheckin
  workspaceBranchId
  workspaceBranch {
    ...WorkspaceBranchData
  }
  location {
    ...LocationData
  }
  secondaryLocation {
    ...LocationData
  }
  vnLocation {
    ...LocationData
  }
  vnSecondaryLocation {
    ...LocationData
  }
  relationshipContacts {
    name
    phone
    type
  }
  assigneeUsers {
    ...WorkspaceMember
  }
  socialFacebookUrl
  presenterCustomerId
  isArchived
  medicalHistory
  source

  vnLocationFullAddress
  vnSecondaryLocationFullAddress

  vnPrevLocationFullAddress
  vnPrevSecondaryLocationFullAddress
}
