import { TimeZone } from './times.types';

export const timeZones: TimeZone[] = [
  {
    id: 'f2b632f8-3a68-4e2a-add5-3b063bc1a450',
    value: 'Dateline Standard Time',
    abbr: 'DST',
    offset: -12,
    text: '(UTC-12:00) International Date Line West',
    utc: ['Etc/GMT+12'],
  },
  {
    id: '6c61fa7b-f813-4783-a412-bac96a2ac725',
    value: 'UTC-11',
    abbr: 'U',
    offset: -11,
    text: '(UTC-11:00) Coordinated Universal Time-11',
    utc: ['Etc/GMT+11', 'Pacific/Midway', 'Pacific/Niue', 'Pacific/Pago_Pago'],
  },
  {
    id: '500191eb-a54c-404c-acd8-0789edff7b29',
    value: 'Hawaiian Standard Time',
    abbr: 'HST',
    offset: -10,
    text: '(UTC-10:00) Hawaii',
    utc: [
      'Etc/GMT+10',
      'Pacific/Honolulu',
      'Pacific/Johnston',
      'Pacific/Rarotonga',
      'Pacific/Tahiti',
    ],
  },
  {
    id: '70154ac8-2a07-4357-a79d-1e4c3d8c28ae',
    value: 'Alaskan Standard Time',
    abbr: 'AKDT',
    offset: -8,
    text: '(UTC-09:00) Alaska',
    utc: [
      'America/Anchorage',
      'America/Juneau',
      'America/Nome',
      'America/Sitka',
      'America/Yakutat',
    ],
  },
  {
    id: '3f5e0af3-c919-447c-ba74-c1a9babdb43e',
    value: 'Pacific Standard Time (Mexico)',
    abbr: 'PDT',
    offset: -7,
    text: '(UTC-08:00) Baja California',
    utc: ['America/Santa_Isabel'],
  },
  {
    id: '59b02a66-85cb-48ad-b1bc-19e8e4225d8a',
    value: 'Pacific Daylight Time',
    abbr: 'PDT',
    offset: -7,
    text: '(UTC-07:00) Pacific Daylight Time (US & Canada)',
    utc: ['America/Los_Angeles', 'America/Tijuana', 'America/Vancouver'],
  },
  {
    id: '7e4fd042-ba67-4b3c-91b3-1d9122989a1c',
    value: 'Pacific Standard Time',
    abbr: 'PST',
    offset: -8,
    text: '(UTC-08:00) Pacific Standard Time (US & Canada)',
    utc: [
      'America/Los_Angeles',
      'America/Tijuana',
      'America/Vancouver',
      'PST8PDT',
    ],
  },
  {
    id: 'b9fb84bf-92b0-4c63-b4ad-c51d25cc4829',
    value: 'US Mountain Standard Time',
    abbr: 'UMST',
    offset: -7,
    text: '(UTC-07:00) Arizona',
    utc: [
      'America/Creston',
      'America/Dawson',
      'America/Dawson_Creek',
      'America/Hermosillo',
      'America/Phoenix',
      'America/Whitehorse',
      'Etc/GMT+7',
    ],
  },
  {
    id: 'ac9603d0-609c-4902-beaf-a9d003fc0805',
    value: 'Mountain Standard Time (Mexico)',
    abbr: 'MDT',
    offset: -6,
    text: '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
    utc: ['America/Chihuahua', 'America/Mazatlan'],
  },
  {
    id: '494bf4b3-e65f-48ad-8e0d-e8ea06135083',
    value: 'Mountain Standard Time',
    abbr: 'MDT',
    offset: -6,
    text: '(UTC-07:00) Mountain Time (US & Canada)',
    utc: [
      'America/Boise',
      'America/Cambridge_Bay',
      'America/Denver',
      'America/Edmonton',
      'America/Inuvik',
      'America/Ojinaga',
      'America/Yellowknife',
      'MST7MDT',
    ],
  },
  {
    id: 'c2d9d789-a660-47cf-b252-1cae8050c5cb',
    value: 'Central America Standard Time',
    abbr: 'CAST',
    offset: -6,
    text: '(UTC-06:00) Central America',
    utc: [
      'America/Belize',
      'America/Costa_Rica',
      'America/El_Salvador',
      'America/Guatemala',
      'America/Managua',
      'America/Tegucigalpa',
      'Etc/GMT+6',
      'Pacific/Galapagos',
    ],
  },
  {
    id: '423f32b0-15d4-4872-b6a8-5c3e23b630e6',
    value: 'Central Standard Time',
    abbr: 'CDT',
    offset: -5,
    text: '(UTC-06:00) Central Time (US & Canada)',
    utc: [
      'America/Chicago',
      'America/Indiana/Knox',
      'America/Indiana/Tell_City',
      'America/Matamoros',
      'America/Menominee',
      'America/North_Dakota/Beulah',
      'America/North_Dakota/Center',
      'America/North_Dakota/New_Salem',
      'America/Rainy_River',
      'America/Rankin_Inlet',
      'America/Resolute',
      'America/Winnipeg',
      'CST6CDT',
    ],
  },
  {
    id: '4e2f9fcb-0e2b-4402-859e-78c92dd36083',
    value: 'Central Standard Time (Mexico)',
    abbr: 'CDT',
    offset: -5,
    text: '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
    utc: [
      'America/Bahia_Banderas',
      'America/Cancun',
      'America/Merida',
      'America/Mexico_City',
      'America/Monterrey',
    ],
  },
  {
    id: '4f4901e9-ae31-4c37-b4de-ec44beb76a01',
    value: 'Canada Central Standard Time',
    abbr: 'CCST',
    offset: -6,
    text: '(UTC-06:00) Saskatchewan',
    utc: ['America/Regina', 'America/Swift_Current'],
  },
  {
    id: '26b8eaa4-e6d7-431b-8d9a-051efb0d8c9d',
    value: 'SA Pacific Standard Time',
    abbr: 'SPST',
    offset: -5,
    text: '(UTC-05:00) Bogota, Lima, Quito',
    utc: [
      'America/Bogota',
      'America/Cayman',
      'America/Coral_Harbour',
      'America/Eirunepe',
      'America/Guayaquil',
      'America/Jamaica',
      'America/Lima',
      'America/Panama',
      'America/Rio_Branco',
      'Etc/GMT+5',
    ],
  },
  {
    id: 'b9196475-4802-492d-a63b-f02a917ac69c',
    value: 'Eastern Standard Time',
    abbr: 'EST',
    offset: -5,
    text: '(UTC-05:00) Eastern Time (US & Canada)',
    utc: [
      'America/Detroit',
      'America/Havana',
      'America/Indiana/Petersburg',
      'America/Indiana/Vincennes',
      'America/Indiana/Winamac',
      'America/Iqaluit',
      'America/Kentucky/Monticello',
      'America/Louisville',
      'America/Montreal',
      'America/Nassau',
      'America/New_York',
      'America/Nipigon',
      'America/Pangnirtung',
      'America/Port-au-Prince',
      'America/Thunder_Bay',
      'America/Toronto',
    ],
  },
  {
    id: 'e49a3717-97cf-4000-9eec-74200f55567d',
    value: 'Eastern Daylight Time',
    abbr: 'EDT',
    offset: -4,
    text: '(UTC-04:00) Eastern Daylight Time (US & Canada)',
    utc: [
      'America/Detroit',
      'America/Havana',
      'America/Indiana/Petersburg',
      'America/Indiana/Vincennes',
      'America/Indiana/Winamac',
      'America/Iqaluit',
      'America/Kentucky/Monticello',
      'America/Louisville',
      'America/Montreal',
      'America/Nassau',
      'America/New_York',
      'America/Nipigon',
      'America/Pangnirtung',
      'America/Port-au-Prince',
      'America/Thunder_Bay',
      'America/Toronto',
    ],
  },
  {
    id: 'a1a21752-2108-42b6-b670-7306da67794a',
    value: 'US Eastern Standard Time',
    abbr: 'UEDT',
    offset: -5,
    text: '(UTC-05:00) Indiana (East)',
    utc: [
      'America/Indiana/Marengo',
      'America/Indiana/Vevay',
      'America/Indianapolis',
    ],
  },
  {
    id: '78ffe1de-ac02-4745-a391-31ed53c85fdc',
    value: 'Venezuela Standard Time',
    abbr: 'VST',
    offset: -4.5,
    text: '(UTC-04:30) Caracas',
    utc: ['America/Caracas'],
  },
  {
    id: 'c2f81a7f-7043-4c60-a585-17c1d5fe23db',
    value: 'Paraguay Standard Time',
    abbr: 'PYT',
    offset: -4,
    text: '(UTC-04:00) Asuncion',
    utc: ['America/Asuncion'],
  },
  {
    id: 'bdf020dc-e6cd-4608-b0cc-0cd5923cf3d5',
    value: 'Atlantic Standard Time',
    abbr: 'ADT',
    offset: -3,
    text: '(UTC-04:00) Atlantic Time (Canada)',
    utc: [
      'America/Glace_Bay',
      'America/Goose_Bay',
      'America/Halifax',
      'America/Moncton',
      'America/Thule',
      'Atlantic/Bermuda',
    ],
  },
  {
    id: '7294aeaa-f448-45f1-a066-440441958919',
    value: 'Central Brazilian Standard Time',
    abbr: 'CBST',
    offset: -4,
    text: '(UTC-04:00) Cuiaba',
    utc: ['America/Campo_Grande', 'America/Cuiaba'],
  },
  {
    id: '56c83d1f-ebf5-4b7e-9e87-ce39ec853950',
    value: 'SA Western Standard Time',
    abbr: 'SWST',
    offset: -4,
    text: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
    utc: [
      'America/Anguilla',
      'America/Antigua',
      'America/Aruba',
      'America/Barbados',
      'America/Blanc-Sablon',
      'America/Boa_Vista',
      'America/Curacao',
      'America/Dominica',
      'America/Grand_Turk',
      'America/Grenada',
      'America/Guadeloupe',
      'America/Guyana',
      'America/Kralendijk',
      'America/La_Paz',
      'America/Lower_Princes',
      'America/Manaus',
      'America/Marigot',
      'America/Martinique',
      'America/Montserrat',
      'America/Port_of_Spain',
      'America/Porto_Velho',
      'America/Puerto_Rico',
      'America/Santo_Domingo',
      'America/St_Barthelemy',
      'America/St_Kitts',
      'America/St_Lucia',
      'America/St_Thomas',
      'America/St_Vincent',
      'America/Tortola',
      'Etc/GMT+4',
    ],
  },
  {
    id: 'd902b86a-5bca-48d4-a04f-bedea87fdb7e',
    value: 'Pacific SA Standard Time',
    abbr: 'PSST',
    offset: -4,
    text: '(UTC-04:00) Santiago',
    utc: ['America/Santiago', 'Antarctica/Palmer'],
  },
  {
    id: 'f26bf0d8-6018-497d-824e-ce199687622c',
    value: 'Newfoundland Standard Time',
    abbr: 'NDT',
    offset: -2.5,
    text: '(UTC-03:30) Newfoundland',
    utc: ['America/St_Johns'],
  },
  {
    id: '36a679d7-51a3-46fd-b98a-0bf76ac3888e',
    value: 'E. South America Standard Time',
    abbr: 'ESAST',
    offset: -3,
    text: '(UTC-03:00) Brasilia',
    utc: ['America/Sao_Paulo'],
  },
  {
    id: '158a8654-df7e-4d55-925b-49d0cc73dcfc',
    value: 'Argentina Standard Time',
    abbr: 'AST',
    offset: -3,
    text: '(UTC-03:00) Buenos Aires',
    utc: [
      'America/Argentina/Buenos_Aires',
      'America/Argentina/Catamarca',
      'America/Argentina/Cordoba',
      'America/Argentina/Jujuy',
      'America/Argentina/La_Rioja',
      'America/Argentina/Mendoza',
      'America/Argentina/Rio_Gallegos',
      'America/Argentina/Salta',
      'America/Argentina/San_Juan',
      'America/Argentina/San_Luis',
      'America/Argentina/Tucuman',
      'America/Argentina/Ushuaia',
      'America/Buenos_Aires',
      'America/Catamarca',
      'America/Cordoba',
      'America/Jujuy',
      'America/Mendoza',
    ],
  },
  {
    id: 'b57415b9-c767-42ad-93b3-f5399f10eaf3',
    value: 'SA Eastern Standard Time',
    abbr: 'SEST',
    offset: -3,
    text: '(UTC-03:00) Cayenne, Fortaleza',
    utc: [
      'America/Araguaina',
      'America/Belem',
      'America/Cayenne',
      'America/Fortaleza',
      'America/Maceio',
      'America/Paramaribo',
      'America/Recife',
      'America/Santarem',
      'Antarctica/Rothera',
      'Atlantic/Stanley',
      'Etc/GMT+3',
    ],
  },
  {
    id: '331847f1-2a40-4b12-a25e-ac5ce714184b',
    value: 'Greenland Standard Time',
    abbr: 'GDT',
    offset: -3,
    text: '(UTC-03:00) Greenland',
    utc: ['America/Godthab'],
  },
  {
    id: 'a30a7441-3023-4061-9e6e-b38a7f24ecd4',
    value: 'Montevideo Standard Time',
    abbr: 'MST',
    offset: -3,
    text: '(UTC-03:00) Montevideo',
    utc: ['America/Montevideo'],
  },
  {
    id: 'b36f1254-eb78-4c75-94be-0fc27d310665',
    value: 'Bahia Standard Time',
    abbr: 'BST',
    offset: -3,
    text: '(UTC-03:00) Salvador',
    utc: ['America/Bahia'],
  },
  {
    id: 'fe83e59b-e9c2-4693-861a-3c9aa4548275',
    value: 'UTC-02',
    abbr: 'U',
    offset: -2,
    text: '(UTC-02:00) Coordinated Universal Time-02',
    utc: ['America/Noronha', 'Atlantic/South_Georgia', 'Etc/GMT+2'],
  },
  {
    id: 'ca37ed32-c935-40f5-8fd1-dbe82c7f1bdf',
    value: 'Mid-Atlantic Standard Time',
    abbr: 'MDT',
    offset: -1,
    text: '(UTC-02:00) Mid-Atlantic - Old',
    utc: [],
  },
  {
    id: 'f64ac5c2-3b3c-421b-8251-2b1688a21294',
    value: 'Azores Standard Time',
    abbr: 'ADT',
    offset: 0,
    text: '(UTC-01:00) Azores',
    utc: ['America/Scoresbysund', 'Atlantic/Azores'],
  },
  {
    id: '47d5cca8-8bd9-47b9-8be9-5b97d9b6e69d',
    value: 'Cape Verde Standard Time',
    abbr: 'CVST',
    offset: -1,
    text: '(UTC-01:00) Cape Verde Is.',
    utc: ['Atlantic/Cape_Verde', 'Etc/GMT+1'],
  },
  {
    id: '112305f1-4c8d-496f-bb3b-c10f7ce915d1',
    value: 'Morocco Standard Time',
    abbr: 'MDT',
    offset: 1,
    text: '(UTC) Casablanca',
    utc: ['Africa/Casablanca', 'Africa/El_Aaiun'],
  },
  {
    id: 'b4db9d23-c3d5-4ec4-b63c-34539237b8a7',
    value: 'UTC',
    abbr: 'UTC',
    offset: 0,
    text: '(UTC) Coordinated Universal Time',
    utc: ['America/Danmarkshavn', 'Etc/GMT'],
  },
  {
    id: '36ad80d0-aa6d-4c19-8355-c50bc9bd613b',
    value: 'GMT Standard Time',
    abbr: 'GMT',
    offset: 0,
    text: '(UTC) Edinburgh, London',
    utc: [
      'Europe/Isle_of_Man',
      'Europe/Guernsey',
      'Europe/Jersey',
      'Europe/London',
    ],
  },
  {
    id: '3117f82a-9b2d-432e-97c9-161749d011a9',
    value: 'British Summer Time',
    abbr: 'BST',
    offset: 1,
    text: '(UTC+01:00) Edinburgh, London',
    utc: [
      'Europe/Isle_of_Man',
      'Europe/Guernsey',
      'Europe/Jersey',
      'Europe/London',
    ],
  },
  {
    id: '7083efc3-b68a-4080-9607-0a0abf034abf',
    value: 'GMT Standard Time',
    abbr: 'GDT',
    offset: 1,
    text: '(UTC) Dublin, Lisbon',
    utc: [
      'Atlantic/Canary',
      'Atlantic/Faeroe',
      'Atlantic/Madeira',
      'Europe/Dublin',
      'Europe/Lisbon',
    ],
  },
  {
    id: 'b67872da-d73e-4662-b910-0bdd5eda895f',
    value: 'Greenwich Standard Time',
    abbr: 'GST',
    offset: 0,
    text: '(UTC) Monrovia, Reykjavik',
    utc: [
      'Africa/Abidjan',
      'Africa/Accra',
      'Africa/Bamako',
      'Africa/Banjul',
      'Africa/Bissau',
      'Africa/Conakry',
      'Africa/Dakar',
      'Africa/Freetown',
      'Africa/Lome',
      'Africa/Monrovia',
      'Africa/Nouakchott',
      'Africa/Ouagadougou',
      'Africa/Sao_Tome',
      'Atlantic/Reykjavik',
      'Atlantic/St_Helena',
    ],
  },
  {
    id: 'e3c30801-f594-4503-ab50-7aa18e8174ff',
    value: 'W. Europe Standard Time',
    abbr: 'WEDT',
    offset: 2,
    text: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    utc: [
      'Arctic/Longyearbyen',
      'Europe/Amsterdam',
      'Europe/Andorra',
      'Europe/Berlin',
      'Europe/Busingen',
      'Europe/Gibraltar',
      'Europe/Luxembourg',
      'Europe/Malta',
      'Europe/Monaco',
      'Europe/Oslo',
      'Europe/Rome',
      'Europe/San_Marino',
      'Europe/Stockholm',
      'Europe/Vaduz',
      'Europe/Vatican',
      'Europe/Vienna',
      'Europe/Zurich',
    ],
  },
  {
    id: 'edf4f7a0-f390-450b-bb77-ac0b008487a8',
    value: 'Central Europe Standard Time',
    abbr: 'CEDT',
    offset: 2,
    text: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    utc: [
      'Europe/Belgrade',
      'Europe/Bratislava',
      'Europe/Budapest',
      'Europe/Ljubljana',
      'Europe/Podgorica',
      'Europe/Prague',
      'Europe/Tirane',
    ],
  },
  {
    id: 'a7b92ccd-a87e-479c-82e1-3d5e575580e9',
    value: 'Romance Standard Time',
    abbr: 'RDT',
    offset: 2,
    text: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
    utc: [
      'Africa/Ceuta',
      'Europe/Brussels',
      'Europe/Copenhagen',
      'Europe/Madrid',
      'Europe/Paris',
    ],
  },
  {
    id: '20f20815-fe44-4c67-80e9-aaf11a1b66b2',
    value: 'Central European Standard Time',
    abbr: 'CEDT',
    offset: 2,
    text: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
    utc: ['Europe/Sarajevo', 'Europe/Skopje', 'Europe/Warsaw', 'Europe/Zagreb'],
  },
  {
    id: 'd99551a1-eaa7-4780-b128-66672006f3a8',
    value: 'W. Central Africa Standard Time',
    abbr: 'WCAST',
    offset: 1,
    text: '(UTC+01:00) West Central Africa',
    utc: [
      'Africa/Algiers',
      'Africa/Bangui',
      'Africa/Brazzaville',
      'Africa/Douala',
      'Africa/Kinshasa',
      'Africa/Lagos',
      'Africa/Libreville',
      'Africa/Luanda',
      'Africa/Malabo',
      'Africa/Ndjamena',
      'Africa/Niamey',
      'Africa/Porto-Novo',
      'Africa/Tunis',
      'Etc/GMT-1',
    ],
  },
  {
    id: 'af3cbb70-2ff3-4526-af24-14060d22e2b8',
    value: 'Namibia Standard Time',
    abbr: 'NST',
    offset: 1,
    text: '(UTC+01:00) Windhoek',
    utc: ['Africa/Windhoek'],
  },
  {
    id: 'e762a3d2-baba-400f-ac44-e25399628143',
    value: 'GTB Standard Time',
    abbr: 'GDT',
    offset: 3,
    text: '(UTC+02:00) Athens, Bucharest',
    utc: [
      'Asia/Nicosia',
      'Europe/Athens',
      'Europe/Bucharest',
      'Europe/Chisinau',
    ],
  },
  {
    id: '2f32e43c-4c59-4359-a0cc-0ae4c9587e77',
    value: 'Middle East Standard Time',
    abbr: 'MEDT',
    offset: 3,
    text: '(UTC+02:00) Beirut',
    utc: ['Asia/Beirut'],
  },
  {
    id: '367d051b-016f-4afd-84ed-71dadbec27df',
    value: 'Egypt Standard Time',
    abbr: 'EST',
    offset: 2,
    text: '(UTC+02:00) Cairo',
    utc: ['Africa/Cairo'],
  },
  {
    id: '30516589-72ee-41ca-90ea-6e2286621e9a',
    value: 'Syria Standard Time',
    abbr: 'SDT',
    offset: 3,
    text: '(UTC+02:00) Damascus',
    utc: ['Asia/Damascus'],
  },
  {
    id: 'e3243c1a-d773-4d3a-a1ce-d1576cca88ec',
    value: 'E. Europe Standard Time',
    abbr: 'EEDT',
    offset: 3,
    text: '(UTC+02:00) E. Europe',
    utc: [
      'Asia/Nicosia',
      'Europe/Athens',
      'Europe/Bucharest',
      'Europe/Chisinau',
      'Europe/Helsinki',
      'Europe/Kyiv',
      'Europe/Mariehamn',
      'Europe/Nicosia',
      'Europe/Riga',
      'Europe/Sofia',
      'Europe/Tallinn',
      'Europe/Uzhhorod',
      'Europe/Vilnius',
      'Europe/Zaporizhzhia',
    ],
  },
  {
    id: '67d2135c-2c4b-4d59-9665-b8aca4d67b03',
    value: 'South Africa Standard Time',
    abbr: 'SAST',
    offset: 2,
    text: '(UTC+02:00) Harare, Pretoria',
    utc: [
      'Africa/Blantyre',
      'Africa/Bujumbura',
      'Africa/Gaborone',
      'Africa/Harare',
      'Africa/Johannesburg',
      'Africa/Kigali',
      'Africa/Lubumbashi',
      'Africa/Lusaka',
      'Africa/Maputo',
      'Africa/Maseru',
      'Africa/Mbabane',
      'Etc/GMT-2',
    ],
  },
  {
    id: '3eac2f61-cfa5-4e4e-812b-d2c80d6dac36',
    value: 'FLE Standard Time',
    abbr: 'FDT',
    offset: 3,
    text: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
    utc: [
      'Europe/Helsinki',
      'Europe/Kyiv',
      'Europe/Mariehamn',
      'Europe/Riga',
      'Europe/Sofia',
      'Europe/Tallinn',
      'Europe/Uzhhorod',
      'Europe/Vilnius',
      'Europe/Zaporizhzhia',
    ],
  },
  {
    id: '413e9508-45e4-4560-a99a-0b02e93ea793',
    value: 'Turkey Standard Time',
    abbr: 'TDT',
    offset: 3,
    text: '(UTC+03:00) Istanbul',
    utc: ['Europe/Istanbul'],
  },
  {
    id: '1a08a751-67f0-4425-8e77-05cf8b492cd1',
    value: 'Israel Standard Time',
    abbr: 'JDT',
    offset: 3,
    text: '(UTC+02:00) Jerusalem',
    utc: ['Asia/Jerusalem'],
  },
  {
    id: 'b2c2839e-96a0-4c10-b86e-13d05e5665a5',
    value: 'Libya Standard Time',
    abbr: 'LST',
    offset: 2,
    text: '(UTC+02:00) Tripoli',
    utc: ['Africa/Tripoli'],
  },
  {
    id: '65c34c8e-e19f-4540-b559-fe2971cbcfc4',
    value: 'Jordan Standard Time',
    abbr: 'JST',
    offset: 3,
    text: '(UTC+03:00) Amman',
    utc: ['Asia/Amman'],
  },
  {
    id: 'daef38e1-78b0-4dfd-8f9b-ae7cddd5503b',
    value: 'Arabic Standard Time',
    abbr: 'AST',
    offset: 3,
    text: '(UTC+03:00) Baghdad',
    utc: ['Asia/Baghdad'],
  },
  {
    id: 'be43cdfe-0acc-4803-97b5-19d0e1cb8238',
    value: 'Kaliningrad Standard Time',
    abbr: 'KST',
    offset: 3,
    text: '(UTC+02:00) Kaliningrad',
    utc: ['Europe/Kaliningrad'],
  },
  {
    id: '034bc2d1-a2ac-4bb3-8e02-bb3e1d435250',
    value: 'Arab Standard Time',
    abbr: 'AST',
    offset: 3,
    text: '(UTC+03:00) Kuwait, Riyadh',
    utc: [
      'Asia/Aden',
      'Asia/Bahrain',
      'Asia/Kuwait',
      'Asia/Qatar',
      'Asia/Riyadh',
    ],
  },
  {
    id: '7c6e2998-4f9d-46a3-be8f-930ab5e5d5b3',
    value: 'E. Africa Standard Time',
    abbr: 'EAST',
    offset: 3,
    text: '(UTC+03:00) Nairobi',
    utc: [
      'Africa/Addis_Ababa',
      'Africa/Asmera',
      'Africa/Dar_es_Salaam',
      'Africa/Djibouti',
      'Africa/Juba',
      'Africa/Kampala',
      'Africa/Khartoum',
      'Africa/Mogadishu',
      'Africa/Nairobi',
      'Antarctica/Syowa',
      'Etc/GMT-3',
      'Indian/Antananarivo',
      'Indian/Comoro',
      'Indian/Mayotte',
    ],
  },
  {
    id: 'bdfce5cd-99fb-435b-b914-1f7e9c724bbe',
    value: 'Moscow Standard Time',
    abbr: 'MSK',
    offset: 3,
    text: '(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk',
    utc: [
      'Europe/Kirov',
      'Europe/Moscow',
      'Europe/Simferopol',
      'Europe/Volgograd',
      'Europe/Minsk',
    ],
  },
  {
    id: '961ec649-b6a5-4392-8bf8-a78f2c0dee29',
    value: 'Samara Time',
    abbr: 'SAMT',
    offset: 4,
    text: '(UTC+04:00) Samara, Ulyanovsk, Saratov',
    utc: ['Europe/Astrakhan', 'Europe/Samara', 'Europe/Ulyanovsk'],
  },
  {
    id: '05c752ce-1e5d-4f1e-a8e0-0372066f50a6',
    value: 'Iran Standard Time',
    abbr: 'IDT',
    offset: 4.5,
    text: '(UTC+03:30) Tehran',
    utc: ['Asia/Tehran'],
  },
  {
    id: 'bbcce778-2a54-4e30-bcb8-f3538c0d2849',
    value: 'Arabian Standard Time',
    abbr: 'AST',
    offset: 4,
    text: '(UTC+04:00) Abu Dhabi, Muscat',
    utc: ['Asia/Dubai', 'Asia/Muscat', 'Etc/GMT-4'],
  },
  {
    id: '2103edf1-b600-4f4a-ad8c-55b9eaf5d6a5',
    value: 'Azerbaijan Standard Time',
    abbr: 'ADT',
    offset: 5,
    text: '(UTC+04:00) Baku',
    utc: ['Asia/Baku'],
  },
  {
    id: 'f6595bcc-05ed-4edc-87d7-d48fd5ffc5da',
    value: 'Mauritius Standard Time',
    abbr: 'MST',
    offset: 4,
    text: '(UTC+04:00) Port Louis',
    utc: ['Indian/Mahe', 'Indian/Mauritius', 'Indian/Reunion'],
  },
  {
    id: '4961c7a5-6630-460a-a26f-e5119e916598',
    value: 'Georgian Standard Time',
    abbr: 'GET',
    offset: 4,
    text: '(UTC+04:00) Tbilisi',
    utc: ['Asia/Tbilisi'],
  },
  {
    id: '1c4e16f5-75b7-4cab-8aa3-bc3b3c1d18c2',
    value: 'Caucasus Standard Time',
    abbr: 'CST',
    offset: 4,
    text: '(UTC+04:00) Yerevan',
    utc: ['Asia/Yerevan'],
  },
  {
    id: 'bf0ca138-0418-4cf7-830b-03bdfcba0771',
    value: 'Afghanistan Standard Time',
    abbr: 'AST',
    offset: 4.5,
    text: '(UTC+04:30) Kabul',
    utc: ['Asia/Kabul'],
  },
  {
    id: 'd0df3c33-519e-46b8-bd9f-10256da19548',
    value: 'West Asia Standard Time',
    abbr: 'WAST',
    offset: 5,
    text: '(UTC+05:00) Ashgabat, Tashkent',
    utc: [
      'Antarctica/Mawson',
      'Asia/Aqtau',
      'Asia/Aqtobe',
      'Asia/Ashgabat',
      'Asia/Dushanbe',
      'Asia/Oral',
      'Asia/Samarkand',
      'Asia/Tashkent',
      'Etc/GMT-5',
      'Indian/Kerguelen',
      'Indian/Maldives',
    ],
  },
  {
    id: '18bb2092-7f79-4229-9ff1-bd7c36374d2a',
    value: 'Yekaterinburg Time',
    abbr: 'YEKT',
    offset: 5,
    text: '(UTC+05:00) Yekaterinburg',
    utc: ['Asia/Yekaterinburg'],
  },
  {
    id: '65f8e9d9-bc9a-49cc-a3d6-cc104af051b5',
    value: 'Pakistan Standard Time',
    abbr: 'PKT',
    offset: 5,
    text: '(UTC+05:00) Islamabad, Karachi',
    utc: ['Asia/Karachi'],
  },
  {
    id: 'c5431137-da70-4daa-9f64-fc869f578629',
    value: 'India Standard Time',
    abbr: 'IST',
    offset: 5.5,
    text: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
    utc: ['Asia/Kolkata', 'Asia/Calcutta'],
  },
  {
    id: '8f0f7eea-c53e-4f75-a4b7-bf1029a02f0c',
    value: 'Sri Lanka Standard Time',
    abbr: 'SLST',
    offset: 5.5,
    text: '(UTC+05:30) Sri Jayawardenepura',
    utc: ['Asia/Colombo'],
  },
  {
    id: 'adfe67f1-5231-425e-a9d9-8b10f9399b16',
    value: 'Nepal Standard Time',
    abbr: 'NST',
    offset: 5.75,
    text: '(UTC+05:45) Kathmandu',
    utc: ['Asia/Kathmandu'],
  },
  {
    id: '3460b01d-544f-4b15-a1cd-d7daea357b12',
    value: 'Central Asia Standard Time',
    abbr: 'CAST',
    offset: 6,
    text: '(UTC+06:00) Nur-Sultan (Astana)',
    utc: [
      'Antarctica/Vostok',
      'Asia/Almaty',
      'Asia/Bishkek',
      'Asia/Qyzylorda',
      'Asia/Urumqi',
      'Etc/GMT-6',
      'Indian/Chagos',
    ],
  },
  {
    id: '6a8558ea-bf7c-4ea9-b884-b113905b244f',
    value: 'Bangladesh Standard Time',
    abbr: 'BST',
    offset: 6,
    text: '(UTC+06:00) Dhaka',
    utc: ['Asia/Dhaka', 'Asia/Thimphu'],
  },
  {
    id: 'b8349871-f59c-4992-a25f-1326432abbb6',
    value: 'Myanmar Standard Time',
    abbr: 'MST',
    offset: 6.5,
    text: '(UTC+06:30) Yangon (Rangoon)',
    utc: ['Asia/Rangoon', 'Indian/Cocos'],
  },
  {
    id: 'e1e9b158-2b41-4607-9f2c-3f6592b3762a',
    value: 'SE Asia Standard Time',
    abbr: 'SAST',
    offset: 7,
    text: '(UTC+07:00) Bangkok, Hanoi, Jakarta',
    utc: [
      'Antarctica/Davis',
      'Asia/Bangkok',
      'Asia/Hovd',
      'Asia/Jakarta',
      'Asia/Phnom_Penh',
      'Asia/Pontianak',
      'Asia/Saigon',
      'Asia/Vientiane',
      'Etc/GMT-7',
      'Indian/Christmas',
    ],
  },
  {
    id: '9315de9d-75e8-43aa-87f2-cf6dfa893761',
    value: 'N. Central Asia Standard Time',
    abbr: 'NCAST',
    offset: 7,
    text: '(UTC+07:00) Novosibirsk',
    utc: ['Asia/Novokuznetsk', 'Asia/Novosibirsk', 'Asia/Omsk'],
  },
  {
    id: '82587d34-d56b-42ff-96e1-794218822113',
    value: 'China Standard Time',
    abbr: 'CST',
    offset: 8,
    text: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
    utc: ['Asia/Hong_Kong', 'Asia/Macau', 'Asia/Shanghai'],
  },
  {
    id: '63e39eac-73d0-41c8-8ea3-02aafa00a16b',
    value: 'North Asia Standard Time',
    abbr: 'NAST',
    offset: 8,
    text: '(UTC+08:00) Krasnoyarsk',
    utc: ['Asia/Krasnoyarsk'],
  },
  {
    id: '5478b536-a67a-4874-a248-2908d2c95450',
    value: 'Singapore Standard Time',
    abbr: 'MPST',
    offset: 8,
    text: '(UTC+08:00) Kuala Lumpur, Singapore',
    utc: [
      'Asia/Brunei',
      'Asia/Kuala_Lumpur',
      'Asia/Kuching',
      'Asia/Makassar',
      'Asia/Manila',
      'Asia/Singapore',
      'Etc/GMT-8',
    ],
  },
  {
    id: '20139627-fd62-40b0-902a-8b064f1b4a8b',
    value: 'W. Australia Standard Time',
    abbr: 'WAST',
    offset: 8,
    text: '(UTC+08:00) Perth',
    utc: ['Antarctica/Casey', 'Australia/Perth'],
  },
  {
    id: 'c2bed5a6-f318-4baa-8428-914d42fe3784',
    value: 'Taipei Standard Time',
    abbr: 'TST',
    offset: 8,
    text: '(UTC+08:00) Taipei',
    utc: ['Asia/Taipei'],
  },
  {
    id: 'da33642a-d253-4f53-b5c7-52fca2f14ecb',
    value: 'Ulaanbaatar Standard Time',
    abbr: 'UST',
    offset: 8,
    text: '(UTC+08:00) Ulaanbaatar',
    utc: ['Asia/Choibalsan', 'Asia/Ulaanbaatar'],
  },
  {
    id: 'ce25840b-f4a8-4cf5-8706-2c585e72174e',
    value: 'North Asia East Standard Time',
    abbr: 'NAEST',
    offset: 8,
    text: '(UTC+08:00) Irkutsk',
    utc: ['Asia/Irkutsk'],
  },
  {
    id: 'da73b250-bb5c-426e-b15b-4375afcd9ee0',
    value: 'Japan Standard Time',
    abbr: 'JST',
    offset: 9,
    text: '(UTC+09:00) Osaka, Sapporo, Tokyo',
    utc: [
      'Asia/Dili',
      'Asia/Jayapura',
      'Asia/Tokyo',
      'Etc/GMT-9',
      'Pacific/Palau',
    ],
  },
  {
    id: '4af4c2ba-d880-4357-b5b8-ffa2cbeda2f6',
    value: 'Korea Standard Time',
    abbr: 'KST',
    offset: 9,
    text: '(UTC+09:00) Seoul',
    utc: ['Asia/Pyongyang', 'Asia/Seoul'],
  },
  {
    id: 'be28cbf0-fe85-4205-b4d4-6ba2e6e9c827',
    value: 'Cen. Australia Standard Time',
    abbr: 'CAST',
    offset: 9.5,
    text: '(UTC+09:30) Adelaide',
    utc: ['Australia/Adelaide', 'Australia/Broken_Hill'],
  },
  {
    id: 'a6f1194b-7f68-4b39-8839-5d3b1f3b8280',
    value: 'AUS Central Standard Time',
    abbr: 'ACST',
    offset: 9.5,
    text: '(UTC+09:30) Darwin',
    utc: ['Australia/Darwin'],
  },
  {
    id: '96949e0b-27bc-43ad-a852-c165e9b4c943',
    value: 'E. Australia Standard Time',
    abbr: 'EAST',
    offset: 10,
    text: '(UTC+10:00) Brisbane',
    utc: ['Australia/Brisbane', 'Australia/Lindeman'],
  },
  {
    id: '2ca8f46a-520c-43fe-b276-5c0ec472e212',
    value: 'AUS Eastern Standard Time',
    abbr: 'AEST',
    offset: 10,
    text: '(UTC+10:00) Canberra, Melbourne, Sydney',
    utc: ['Australia/Melbourne', 'Australia/Sydney'],
  },
  {
    id: '04dbc6e5-a84a-4281-b32d-7398ca760e90',
    value: 'West Pacific Standard Time',
    abbr: 'WPST',
    offset: 10,
    text: '(UTC+10:00) Guam, Port Moresby',
    utc: [
      'Antarctica/DumontDUrville',
      'Etc/GMT-10',
      'Pacific/Guam',
      'Pacific/Port_Moresby',
      'Pacific/Saipan',
      'Pacific/Truk',
    ],
  },
  {
    id: '62185aa0-73f6-4da1-9726-cf909a14d056',
    value: 'Tasmania Standard Time',
    abbr: 'TST',
    offset: 10,
    text: '(UTC+10:00) Hobart',
    utc: ['Australia/Currie', 'Australia/Hobart'],
  },
  {
    id: 'bb5ed2c1-8063-4b7c-afb9-c1aec5998f83',
    value: 'Yakutsk Standard Time',
    abbr: 'YST',
    offset: 9,
    text: '(UTC+09:00) Yakutsk',
    utc: ['Asia/Chita', 'Asia/Khandyga', 'Asia/Yakutsk'],
  },
  {
    id: 'cfb02115-1f23-4cd6-8d75-b3f5d8a2f2fb',
    value: 'Central Pacific Standard Time',
    abbr: 'CPST',
    offset: 11,
    text: '(UTC+11:00) Solomon Is., New Caledonia',
    utc: [
      'Antarctica/Macquarie',
      'Etc/GMT-11',
      'Pacific/Efate',
      'Pacific/Guadalcanal',
      'Pacific/Kosrae',
      'Pacific/Noumea',
      'Pacific/Ponape',
    ],
  },
  {
    id: '0698b1f4-c3e8-4c87-92e0-414c01fa01bf',
    value: 'Vladivostok Standard Time',
    abbr: 'VST',
    offset: 11,
    text: '(UTC+11:00) Vladivostok',
    utc: ['Asia/Sakhalin', 'Asia/Ust-Nera', 'Asia/Vladivostok'],
  },
  {
    id: '00656708-4bbb-41d1-ad43-f010534fa548',
    value: 'New Zealand Standard Time',
    abbr: 'NZST',
    offset: 12,
    text: '(UTC+12:00) Auckland, Wellington',
    utc: ['Antarctica/McMurdo', 'Pacific/Auckland'],
  },
  {
    id: '5a239ba3-c152-4e83-9648-f5f148fabed7',
    value: 'UTC+12',
    abbr: 'U',
    offset: 12,
    text: '(UTC+12:00) Coordinated Universal Time+12',
    utc: [
      'Etc/GMT-12',
      'Pacific/Funafuti',
      'Pacific/Kwajalein',
      'Pacific/Majuro',
      'Pacific/Nauru',
      'Pacific/Tarawa',
      'Pacific/Wake',
      'Pacific/Wallis',
    ],
  },
  {
    id: 'f0493f0b-17e0-4fec-a8e5-d8880ce5ab1d',
    value: 'Fiji Standard Time',
    abbr: 'FST',
    offset: 12,
    text: '(UTC+12:00) Fiji',
    utc: ['Pacific/Fiji'],
  },
  {
    id: '432ad8e6-ebf5-413a-b776-2754d2f53201',
    value: 'Magadan Standard Time',
    abbr: 'MST',
    offset: 12,
    text: '(UTC+12:00) Magadan',
    utc: [
      'Asia/Anadyr',
      'Asia/Kamchatka',
      'Asia/Magadan',
      'Asia/Srednekolymsk',
    ],
  },
  {
    id: '2a8b3aee-27d6-47be-9a0b-130aba05aeb7',
    value: 'Kamchatka Standard Time',
    abbr: 'KDT',
    offset: 13,
    text: '(UTC+12:00) Petropavlovsk-Kamchatsky - Old',
    utc: ['Asia/Kamchatka'],
  },
  {
    id: 'aa6ddb3a-bf08-4ee5-84f1-300ebabfa02b',
    value: 'Tonga Standard Time',
    abbr: 'TST',
    offset: 13,
    text: "(UTC+13:00) Nuku'alofa",
    utc: [
      'Etc/GMT-13',
      'Pacific/Enderbury',
      'Pacific/Fakaofo',
      'Pacific/Tongatapu',
    ],
  },
  {
    id: 'baab9415-aee6-44d2-9790-2c783678a6a8',
    value: 'Samoa Standard Time',
    abbr: 'SST',
    offset: 13,
    text: '(UTC+13:00) Samoa',
    utc: ['Pacific/Apia'],
  },
];
