#import "./fragmentWorkspace.graphql"

mutation UpdateWorkspace(
  $name: String!
  $type: WorkspaceType!
  $logo: String
  $location: LocationInput
  $hotline: String
  $phone: String
  $appIcon: String
  $appDomain: String
  $appName: String
  $appColor: String
  $appColorShape: Float
  $locale: AppLocale
) {
  updateWorkspace(
    name: $name
    type: $type
    logo: $logo
    location: $location
    hotline: $hotline
    phone: $phone
    appIcon: $appIcon
    appDomain: $appDomain
    appName: $appName
    appColor: $appColor
    appColorShape: $appColorShape
    locale: $locale
  ) {
    ...Workspace
  }
}
