import { BaseMongoEntity, Query } from "@/types";
import { WorkspaceMemberInfo } from "@/modules/workspace-members/workspace-members-types";

export enum EventVariant {
  INFO = 'INFO',
  WARNING = 'WARNING',
  NEGATIVE = 'NEGATIVE',
  POSITIVE = 'POSITIVE',
}

export enum EventType {
  CUSTOM_FIELDS_NEW = 'CUSTOM_FIELDS_NEW',
  CUSTOM_FIELDS_UPDATED = 'CUSTOM_FIELDS_UPDATED',
  CUSTOM_FIELDS_REMOVED = 'CUSTOM_FIELDS_REMOVED',

  WORKSPACE_NEW = 'WORKSPACE_NEW',
  WORKSPACE_UPDATED = 'WORKSPACE_UPDATED',
  WORKSPACE_ARCHIVED = 'WORKSPACE_ARCHIVED',
  WORKSPACE_INVITE_CODE_UPDATED = 'WORKSPACE_INVITE_CODE_UPDATED',

  WORKSPACE_SETTING_UPDATED = 'WORKSPACE_SETTING_UPDATED',

  WORKSPACE_BRANCH_NEW = 'WORKSPACE_BRANCH_NEW',
  WORKSPACE_BRANCH_UPDATED = 'WORKSPACE_BRANCH_UPDATED',
  WORKSPACE_BRANCH_ARCHIVED = 'WORKSPACE_BRANCH_ARCHIVED',

  WORKSPACE_ROLES_NEW = 'WORKSPACE_ROLES_NEW',
  WORKSPACE_ROLES_UPDATED = 'WORKSPACE_ROLES_UPDATED',
  WORKSPACE_ROLES_REMOVED = 'WORKSPACE_ROLES_REMOVED',

  WORKSPACE_BILLINGS_DEPOSITED = 'WORKSPACE_BILLINGS_DEPOSITED',
  WORKSPACE_BILLINGS_WITHDRAWN = 'WORKSPACE_BILLINGS_WITHDRAWN',
  WORKSPACE_BILLINGS_PAYMENT_NEW = 'WORKSPACE_BILLINGS_PAYMENT_NEW',
  WORKSPACE_BILLINGS_CASHBACK_NEW = 'WORKSPACE_BILLINGS_CASHBACK_NEW',
  WORKSPACE_BILLINGS_PAYMENT_PAID = 'WORKSPACE_BILLINGS_PAYMENT_PAID',

  WORKSPACE_API_APP_CREATED = 'WORKSPACE_API_APP_CREATED',
  WORKSPACE_API_APP_UPDATED = 'WORKSPACE_API_APP_UPDATED',
  WORKSPACE_API_APP_ARCHIVED = 'WORKSPACE_API_APP_ARCHIVED',

  WORKSPACE_SUBSCRIPTION_UPDATED = 'WORKSPACE_SUBSCRIPTION_UPDATED',

  WORKSPACE_MEMBER_JOINED = 'WORKSPACE_MEMBER_JOINED',
  WORKSPACE_MEMBER_LEAVED = 'WORKSPACE_MEMBER_LEAVED',
  WORKSPACE_MEMBER_UPDATED = 'WORKSPACE_MEMBER_UPDATED',
  WORKSPACE_MEMBER_TRANSFER_OWNER = 'WORKSPACE_MEMBER_TRANSFER_OWNER',

  CUSTOMER_NEW = 'CUSTOMER_NEW',
  CUSTOMER_UPDATED = 'CUSTOMER_UPDATED',
  CUSTOMER_ASSIGN_TO_USER = 'CUSTOMER_ASSIGN_TO_USER',
  CUSTOMER_UNASSIGN_USER = 'CUSTOMER_UNASSIGN_USER',
  CUSTOMER_CONTACTS_UPDATED = 'CUSTOMER_CONTACTS_UPDATED',
  CUSTOMER_ARCHIVED = 'CUSTOMER_ARCHIVED',
  CUSTOMER_BULK_UPDATE_WORKSPACE_BRANCH = 'CUSTOMER_BULK_UPDATE_WORKSPACE_BRANCH',

  CUSTOMER_FORM_NEW = 'CUSTOMER_FORM_NEW',
  CUSTOMER_FORM_UPDATED = 'CUSTOMER_FORM_UPDATED',
  CUSTOMER_FORM_ARCHIVED = 'CUSTOMER_FORM_ARCHIVED',

  BOOKING_NEW = 'BOOKING_NEW',
  BOOKING_UPDATED = 'BOOKING_UPDATED',
  BOOKING_CHECKIN = 'BOOKING_CHECKIN',
  BOOKING_IN_PROGRESS = 'BOOKING_IN_PROGRESS',
  BOOKING_COMPLETED = 'BOOKING_COMPLETED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',

  COMMENT_NEW = 'COMMENT_NEW',
  COMMENT_UPDATED = 'COMMENT_UPDATED',
  COMMENT_REMOVED = 'COMMENT_REMOVED',
  COMMENT_PINNED = 'COMMENT_PINNED',
  COMMENT_UNPINNED = 'COMMENT_UNPINNED',

  SYNC_TAGS = 'SYNC_TAGS',
  SYNC_CLIENTS = 'SYNC_CLIENTS',

  TAGS_ARCHIVED = 'TAGS_ARCHIVED',

  PRODUCT_NEW = 'PRODUCT_NEW',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_ARCHIVED = 'PRODUCT_ARCHIVED',

  REPORT_RANGE_SYNCED = 'REPORT_RANGE_SYNCED',
  REPORT_REALTIME_SYNCED = 'REPORT_REALTIME_SYNCED',

  PRODUCT_STOCK_IN = 'PRODUCT_STOCK_IN',
  PRODUCT_STOCK_IN_REVERT = 'PRODUCT_STOCK_IN_REVERT',
  PRODUCT_STOCK_OUT = 'PRODUCT_STOCK_OUT',
  PRODUCT_STOCK_OUT_REVERT = 'PRODUCT_STOCK_OUT_REVERT',
  PRODUCT_STOCK_IN_MULTIPLE = 'PRODUCT_STOCK_IN_MULTIPLE',

  PRODUCT_VOUCHERS_NEW = 'PRODUCT_VOUCHERS_NEW',

  PRODUCT_COMBO_NEW = 'PRODUCT_COMBO_NEW',
  PRODUCT_COMBO_UPDATE = 'PRODUCT_COMBO_UPDATE',

  NOTIFICATION_NEW = 'NOTIFICATION_NEW',
  NOTIFICATION_READED = 'NOTIFICATION_READED',
  NOTIFICATION_LIST_VIEWED = 'NOTIFICATION_LIST_VIEWED',
  NOTIFICATION_CLEANED = 'NOTIFICATION_CLEANED',

  PARTNER_NEW = 'PARTNER_NEW',
  PARTNER_UPDATED = 'PARTNER_UPDATED',
  PARTNER_ARCHIVED = 'PARTNER_ARCHIVED',

  TASK_NEW = 'TASK_NEW',
  TASK_NAME_UPDATED = 'TASK_NAME_UPDATED',
  TASK_DESCRIPTION_UPDATED = 'TASK_DESCRIPTION_UPDATED',
  TASK_PRIORITY_UPDATED = 'TASK_PRIORITY_UPDATED',
  TASK_STATUS_UPDATED = 'TASK_STATUS_UPDATED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_ARCHIVED = 'TASK_ARCHIVED',
  TASKS_UPDATED = 'TASKS_UPDATED',
  TASK_SYNCED = 'TASK_SYNCED',

  FILE_NEW = 'FILE_NEW',
  FILE_REMOVED = 'FILE_REMOVED',

  RECEIPT_NEW = 'RECEIPT_NEW',
  RECEIPT_PAID = 'RECEIPT_PAID',
  RECEIPT_UPDATED = 'RECEIPT_UPDATED',
  RECEIPT_DISBURSEMENT = 'RECEIPT_DISBURSEMENT',
  RECEIPT_ARCHIVED = 'RECEIPT_ARCHIVED',
  RECEIPT_UNARCHIVED = 'RECEIPT_UNARCHIVED',
  RECEIPT_SYNCED = 'RECEIPT_SYNCED',
  RECEIPT_CHANGE_WORKSPACE_BRANCH = 'RECEIPT_CHANGE_WORKSPACE_BRANCH',
  RECEIPT_REVERT_PAYMENT = 'RECEIPT_REVERT_PAYMENT',

  PRODUCT_SUPPLY_RECORD_NEW = 'PRODUCT_SUPPLY_RECORD_NEW',

  PLUGIN_ZALO_OA_ACTIVE = 'PLUGIN_ZALO_OA_ACTIVE',
  PLUGIN_ZALO_OA_INACTIVE = 'PLUGIN_ZALO_OA_INACTIVE',
  PLUGIN_ZALO_OA_UPDATED = 'PLUGIN_ZALO_OA_UPDATED',
  PLUGIN_ZALO_OA_ENABLED = 'PLUGIN_ZALO_OA_ENABLED',
  PLUGIN_ZALO_OA_DISABLED = 'PLUGIN_ZALO_OA_DISABLED',

  PLUGIN_META_PAGES_UPDATED = 'PLUGIN_META_PAGES_UPDATED',
  PLUGIN_META_PAGES_DISCONNECTED = 'PLUGIN_META_PAGES_DISCONNECTED',

  HRM_TIMEKEEPING_MEMBER_CHECK_IN = 'HRM_TIMEKEEPING_MEMBER_CHECK_IN',
  HRM_TIMEKEEPING_MEMBER_CHECK_OUT = 'HRM_TIMEKEEPING_MEMBER_CHECK_OUT',
  HRM_TIMEKEEPING_MANUAL_APPROVAL = 'HRM_TIMEKEEPING_MANUAL_APPROVAL',
  HRM_TIMEKEEPING_REJECTED = 'HRM_TIMEKEEPING_REJECTED',
  HRM_TIMEKEEPING_REMOVED = 'HRM_TIMEKEEPING_REMOVED',

  PRESCRIPTIONS_NEW = 'PRESCRIPTIONS_NEW',
  PRESCRIPTIONS_UPDATED = 'PRESCRIPTIONS_UPDATED',
  PRESCRIPTIONS_REMOVED = 'PRESCRIPTIONS_REMOVED',

  MESSAGE_BOX_NEW = 'MESSAGE_BOX_NEW',
  MESSAGE_BOX_WAITING = 'MESSAGE_BOX_WAITING',
  MESSAGE_BOX_NEW_MESSAGE = 'MESSAGE_BOX_NEW_MESSAGE',
  MESSAGE_BOX_IN_PROGRESS = 'MESSAGE_BOX_IN_PROGRESS',
  MESSAGE_BOX_REMOVED = 'MESSAGE_BOX_REMOVED',
  MESSAGE_BOX_CLOSED = 'MESSAGE_BOX_CLOSED',
  MESSAGE_BOX_UPDATED = 'MESSAGE_BOX_UPDATED',

  MESSAGE_NEW = 'MESSAGE_NEW',
  MESSAGE_UPDATED = 'MESSAGE_UPDATED',

  TABLE_SLOT_NEW = 'TABLE_SLOT_NEW',
  TABLE_SLOT_UPDATED = 'TABLE_SLOT_UPDATED',
  TABLE_SLOT_ARCHIVED = 'TABLE_SLOT_ARCHIVED',

  BANK_TRANSACTION_PAID = 'BANK_TRANSACTION_PAID',
  BANK_TRANSACTION_FULFILLED = 'BANK_TRANSACTION_FULFILLED',
  BANK_TRANSACTION_CANCELLED = 'BANK_TRANSACTION_CANCELLED',
  BANK_TRANSACTION_FAILED = 'BANK_TRANSACTION_FAILED',

  CUSTOMER_KYC_PENDING = 'CUSTOMER_KYC_PENDING',
  CUSTOMER_KYC_APPROVED = 'CUSTOMER_KYC_APPROVED',
  CUSTOMER_KYC_REJECTED = 'CUSTOMER_KYC_REJECTED',

  LOANS_JUST_CREATED = 'LOANS_JUST_CREATED',
  LOANS_PENDING = 'LOANS_PENDING',
  LOANS_APPROVED = 'LOANS_APPROVED',
  LOANS_APPROVED_REVERTED = 'LOANS_APPROVED_REVERTED',
  LOANS_REJECTED = 'LOANS_REJECTED',
  LOANS_REVERT_REJECTED = 'LOANS_REVERT_REJECTED',
  LOANS_UPDATED = 'LOANS_UPDATED',
  LOANS_SYNCED = 'LOANS_SYNCED',
  LOANS_FULFILLED = 'LOANS_FULFILLED',
  LOANS_COMPLETED = 'LOANS_COMPLETED',
  LOANS_ARCHIVED = 'LOANS_ARCHIVED',
  LOANS_LIQUIDATION = 'LOANS_LIQUIDATION',
  LOANS_REVERT_LIQUIDATION = 'LOANS_REVERT_LIQUIDATION',
  LOANS_CHANGE_WORKSPACE_BRANCH = 'LOANS_CHANGE_WORKSPACE_BRANCH',

  COUPON_RULES_CREATED = 'COUPON_RULES_CREATED',
  COUPON_RULES_UPDATED = 'COUPON_RULES_UPDATED',
  COUPON_RULES_ARCHIVED = 'COUPON_RULES_ARCHIVED',

  COUPONS_CREATED = 'COUPONS_CREATED',
  COUPONS_USED = 'COUPONS_USED',

  PLUGIN_MESSAGE_HUBS_NEW = 'PLUGIN_MESSAGE_HUBS_NEW',
  PLUGIN_MESSAGE_HUBS_UPDATED = 'PLUGIN_MESSAGE_HUBS_UPDATED',
  PLUGIN_MESSAGE_HUBS_REMOVED = 'PLUGIN_MESSAGE_HUBS_REMOVED',

  PLUGIN_AI_ASSISTANTS_NEW = 'PLUGIN_AI_ASSISTANTS_NEW',
  PLUGIN_AI_ASSISTANTS_UPDATED = 'PLUGIN_AI_ASSISTANTS_UPDATED',
  PLUGIN_AI_ASSISTANTS_REMOVED = 'PLUGIN_AI_ASSISTANTS_REMOVED',

  USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',

  ORDER_NEW = 'ORDER_NEW',
  ORDER_UPDATED = 'ORDER_UPDATED',
  ORDER_ARCHIVED = 'ORDER_ARCHIVED',
  ORDER_SYNCED = 'ORDER_SYNCED',

  POST_NEW = 'POST_NEW',
  POST_UPDATED = 'POST_UPDATED',
  POST_ARCHIVED = 'POST_ARCHIVED',

  CATEGORY_NEW = 'CATEGORY_NEW',
  CATEGORY_UPDATED = 'CATEGORY_UPDATED',
  CATEGORY_ARCHIVED = 'CATEGORY_ARCHIVED',

  PROMOTION_NEW = 'PROMOTION_NEW',
  PROMOTION_UPDATED = 'PROMOTION_UPDATED',
  PROMOTION_ARCHIVED = 'PROMOTION_ARCHIVED',
}

export interface EventEntity extends BaseMongoEntity {
  ref?: string;
  workspaceId: string;
  type: EventType;
  variant?: EventVariant;
  time: number;
  userId?: string;
  user?: WorkspaceMemberInfo;
  data?: any;
  sessionId?: string;
}

export interface QueryEvents extends Query {
  type?: EventType | EventType[];
  userId?: string;
  ref?: string;
}

export interface UserEventDto {
  userId: string;
  eventName: string;
  data?: any;
}