import { EventType } from "@/graphql/enums.graphql";
import { defineMessage, MacroMessageDescriptor } from "@lingui/core/macro";
import {
  Icon,
  IconAlertTriangle,
  IconCheck,
  IconExclamationMark,
  IconHistoryToggle,
} from "@tabler/icons-react";
import { EventVariant } from "./event-types";

export const eventVariants: Record<
  EventVariant,
  { name: MacroMessageDescriptor; color: string; icon: Icon }
> = {
  [EventVariant.INFO]: { name: defineMessage`Info`, color: "gray", icon: IconHistoryToggle },
  [EventVariant.WARNING]: {
    name: defineMessage`Warning`,
    color: "orange",
    icon: IconAlertTriangle,
  },
  [EventVariant.NEGATIVE]: {
    name: defineMessage`Negative`,
    color: "red",
    icon: IconExclamationMark,
  },
  [EventVariant.POSITIVE]: { name: defineMessage`Positive`, color: "green", icon: IconCheck },
};

export const eventTypes: Partial<Record<EventType, { name: MacroMessageDescriptor }>> = {
  [EventType.CustomFieldsNew]: { name: defineMessage`Custom field created` },
  [EventType.CustomFieldsUpdated]: { name: defineMessage`Custom field updated` },
  [EventType.CustomFieldsRemoved]: { name: defineMessage`Custom field removed` },
  [EventType.WorkspaceNew]: { name: defineMessage`Workspace created` },
  [EventType.WorkspaceUpdated]: { name: defineMessage`Workspace updated` },
  [EventType.WorkspaceSettingUpdated]: { name: defineMessage`Workspace setting updated` },
  [EventType.WorkspaceMemberJoined]: { name: defineMessage`Member joined workspace` },
  [EventType.WorkspaceMemberLeaved]: { name: defineMessage`Member leaved workspace` },
  [EventType.WorkspaceMemberUpdated]: { name: defineMessage`Member updated` },
  [EventType.WorkspaceMemberTransferOwner]: { name: defineMessage`Transfer owner` },
  [EventType.CustomerNew]: { name: defineMessage`Customer created` },
  [EventType.CustomerUpdated]: { name: defineMessage`Customer updated` },
  [EventType.CustomerAssignToUser]: { name: defineMessage`Assign user` },
  [EventType.CustomerUnassignUser]: { name: defineMessage`Unassign user` },
  [EventType.CustomerBulkUpdateWorkspaceBranch]: {
    name: defineMessage`Bulk update workspace branch`,
  },
  [EventType.BookingNew]: { name: defineMessage`Create booking` },
  [EventType.BookingUpdated]: { name: defineMessage`Update booking` },
  [EventType.BookingCheckin]: { name: defineMessage`Customer checkin` },
  [EventType.BookingInProgress]: { name: defineMessage`Next customer` },
  [EventType.BookingCompleted]: { name: defineMessage`Booking Completed` },
  [EventType.BookingCancelled]: { name: defineMessage`Booking Cancelled` },
  [EventType.CommentNew]: { name: defineMessage`Comment created` },
  [EventType.CommentUpdated]: { name: defineMessage`Comment updated` },
  [EventType.CommentRemoved]: { name: defineMessage`Comment removed` },
  [EventType.CommentPinned]: { name: defineMessage`Comment pinned` },
  [EventType.CommentUnpinned]: { name: defineMessage`Comment unpinned` },
  [EventType.ProductNew]: { name: defineMessage`Create product` },
  [EventType.ProductUpdate]: { name: defineMessage`Update product` },
  [EventType.ProductArchived]: { name: defineMessage`Archive product` },
  [EventType.ReportRangeSynced]: { name: defineMessage`Report synced` },
  [EventType.NotificationNew]: { name: defineMessage`New notification` },
  [EventType.NotificationReaded]: { name: defineMessage`Mark as read` },
  [EventType.NotificationListViewed]: { name: defineMessage`View notification list` },
  [EventType.NotificationCleaned]: { name: defineMessage`Clean notifications` },
  [EventType.PartnerNew]: { name: defineMessage`Create partner` },
  [EventType.PartnerUpdated]: { name: defineMessage`Update partner` },
  [EventType.PartnerArchived]: { name: defineMessage`Archive partner` },
  [EventType.TaskNew]: { name: defineMessage`Create task` },
  [EventType.TaskArchived]: { name: defineMessage`Archive task` },
  [EventType.FileNew]: { name: defineMessage`Create file` },
  [EventType.FileRemoved]: { name: defineMessage`Remove file` },
  [EventType.ReceiptNew]: { name: defineMessage`Create receipt` },
  [EventType.ReceiptPaid]: { name: defineMessage`Pay receipt` },
  [EventType.ReceiptUpdated]: { name: defineMessage`Update receipt` },
  [EventType.ReceiptDisbursement]: { name: defineMessage`Disbursement` },
  [EventType.ReceiptArchived]: { name: defineMessage`Archive receipt` },
  [EventType.ProductSupplyRecordNew]: { name: defineMessage`Product supply record created` },
  [EventType.PluginZaloOaActive]: { name: defineMessage`Zalo OA active` },
  [EventType.PluginZaloOaInactive]: { name: defineMessage`Zalo OA inactive` },
  [EventType.PluginZaloOaUpdated]: { name: defineMessage`Zalo OA updated` },
  [EventType.PluginZaloOaEnabled]: { name: defineMessage`Zalo OA enabled` },
  [EventType.PluginZaloOaDisabled]: { name: defineMessage`Zalo OA disabled` },
  [EventType.PluginMetaPagesUpdated]: { name: defineMessage`Meta pages updated` },
  [EventType.PluginMetaPagesDisconnected]: { name: defineMessage`Meta pages disconnected` },
  [EventType.HrmTimekeepingMemberCheckIn]: { name: defineMessage`Member check in` },
  [EventType.HrmTimekeepingMemberCheckOut]: { name: defineMessage`Member check out` },
  [EventType.HrmTimekeepingManualApproval]: { name: defineMessage`Manual approval timekeeping` },
  [EventType.HrmTimekeepingRejected]: { name: defineMessage`Rejected timekeeping` },
  [EventType.HrmTimekeepingRemoved]: { name: defineMessage`Removed timekeeping` },
  [EventType.WorkspaceRolesNew]: { name: defineMessage`Role created` },
  [EventType.WorkspaceRolesUpdated]: { name: defineMessage`Role updated` },
  [EventType.WorkspaceRolesRemoved]: { name: defineMessage`Role removed` },
  [EventType.PrescriptionsNew]: { name: defineMessage`Prescription created` },
  [EventType.PrescriptionsUpdated]: { name: defineMessage`Prescription updated` },
  [EventType.PrescriptionsRemoved]: { name: defineMessage`Prescription removed` },
  [EventType.MessageNew]: { name: defineMessage`New message` },
  [EventType.MessageUpdated]: { name: defineMessage`Message updated` },
  [EventType.MessageBoxNew]: { name: defineMessage`New message box` },
  [EventType.MessageBoxWaiting]: { name: defineMessage`Message box waiting` },
  [EventType.MessageBoxNewMessage]: { name: defineMessage`New message in box` },
  [EventType.MessageBoxInProgress]: { name: defineMessage`Message box in progress` },
  [EventType.MessageBoxRemoved]: { name: defineMessage`Message box removed` },
  [EventType.MessageBoxClosed]: { name: defineMessage`Message box closed` },
  [EventType.MessageBoxUpdated]: { name: defineMessage`Message box updated` },
  [EventType.WorkspaceBillingsDeposited]: { name: defineMessage`Billings deposited` },
  [EventType.WorkspaceBillingsWithdrawn]: { name: defineMessage`Billings withdrawn` },
  [EventType.WorkspaceBillingsPaymentNew]: { name: defineMessage`Payment created` },
  [EventType.WorkspaceBillingsCashbackNew]: { name: defineMessage`Cashback created` },
  [EventType.WorkspaceBillingsPaymentPaid]: { name: defineMessage`Payment paid` },
  [EventType.WorkspaceSubscriptionUpdated]: { name: defineMessage`Subscription updated` },
  [EventType.TableSlotNew]: { name: defineMessage`Table slot created` },
  [EventType.TableSlotUpdated]: { name: defineMessage`Table slot updated` },
  [EventType.TableSlotArchived]: { name: defineMessage`Table slot archived` },
  [EventType.BankTransactionPaid]: { name: defineMessage`Transaction paid` },
  [EventType.BankTransactionFulfilled]: { name: defineMessage`Transaction fulfilled` },
  [EventType.BankTransactionCancelled]: { name: defineMessage`Transaction cancelled` },
  [EventType.BankTransactionFailed]: { name: defineMessage`Transaction failed` },
  [EventType.CustomerKycPending]: { name: defineMessage`KYC pending` },
  [EventType.CustomerKycApproved]: { name: defineMessage`KYC approved` },
  [EventType.CustomerKycRejected]: { name: defineMessage`KYC rejected` },
  [EventType.LoansPending]: {
    name: defineMessage`Loan is signed by customer, waiting for approval`,
  },
  [EventType.LoansApproved]: { name: defineMessage`Approve loan` },
  [EventType.LoansRejected]: { name: defineMessage`Reject loan` },
  [EventType.LoansUpdated]: { name: defineMessage`Update loan` },
  [EventType.LoansFulfilled]: { name: defineMessage`Fulfill loan` },
  [EventType.LoansCompleted]: { name: defineMessage`Complete loan` },
  [EventType.LoansJustCreated]: { name: defineMessage`Create new loan contract` },
  [EventType.CouponRulesArchived]: { name: defineMessage`Coupon archived` },
  [EventType.CouponRulesCreated]: { name: defineMessage`Coupon created` },
  [EventType.CouponRulesUpdated]: { name: defineMessage`Coupon updated` },
  [EventType.CouponsCreated]: { name: defineMessage`Coupon created` },
  [EventType.CouponsUsed]: { name: defineMessage`Coupon used` },
  [EventType.LoansArchived]: { name: defineMessage`Loans archived` },
  [EventType.LoansLiquidation]: { name: defineMessage`Loans liquidation` },
  [EventType.CustomerContactsUpdated]: { name: defineMessage`Customer contacts updated` },
  [EventType.ProductVouchersNew]: { name: defineMessage`New voucher` },
  [EventType.PluginMessageHubsNew]: { name: defineMessage`New message hub` },
  [EventType.PluginMessageHubsUpdated]: { name: defineMessage`Message hub updated` },
  [EventType.PluginMessageHubsRemoved]: { name: defineMessage`Message hub removed` },
  [EventType.WorkspaceArchived]: { name: defineMessage`Workspace archived` },
  [EventType.TagsArchived]: { name: defineMessage`Tags archived` },
  [EventType.TasksUpdated]: { name: defineMessage`Tasks updated` },
  [EventType.TaskStatusUpdated]: { name: defineMessage`Update task status` },
  [EventType.TaskAssigned]: { name: defineMessage`Task assigned` },
  [EventType.ReceiptUnarchived]: { name: defineMessage`Receipt unarchived` },
  [EventType.LoansRevertLiquidation]: { name: defineMessage`Revert liquidation` },
  [EventType.CustomerArchived]: { name: defineMessage`Customer archived` },
  [EventType.TaskNameUpdated]: { name: defineMessage`Update task name` },
  [EventType.TaskDescriptionUpdated]: { name: defineMessage`Update task description` },
  [EventType.TaskPriorityUpdated]: { name: defineMessage`Update task priority` },
  [EventType.UserProfileUpdated]: { name: defineMessage`Update user profile` },
  [EventType.WorkspaceInviteCodeUpdated]: { name: defineMessage`Workspace invite code updated` },
  [EventType.PluginAiAssistantsNew]: { name: defineMessage`AI assistant created` },
  [EventType.PluginAiAssistantsUpdated]: { name: defineMessage`AI assistant updated` },
  [EventType.PluginAiAssistantsRemoved]: { name: defineMessage`AI assistant removed` },
  [EventType.WorkspaceBranchNew]: { name: defineMessage`Create new workspace branch` },
  [EventType.WorkspaceBranchUpdated]: { name: defineMessage`Update workspace branch` },
  [EventType.OrderNew]: { name: defineMessage`Created order` },
  [EventType.OrderUpdated]: { name: defineMessage`Updated order` },
  [EventType.OrderArchived]: { name: defineMessage`Archived order` },
  [EventType.ProductComboUpdate]: { name: defineMessage`Product combo updated` },
  [EventType.OrderSynced]: { name: defineMessage`Order synced` },
  [EventType.LoansSynced]: { name: defineMessage`Loans synced` },
  [EventType.ProductStockIn]: { name: defineMessage`Stock in` },
  [EventType.ProductStockInRevert]: { name: defineMessage`Stock in reverted` },
  [EventType.ProductStockOut]: { name: defineMessage`Stock out` },
  [EventType.ProductStockOutRevert]: { name: defineMessage`Stock out reverted` },
  [EventType.ProductStockInMultiple]: { name: defineMessage`Stock in multiple` },
  [EventType.ProductComboNew]: { name: defineMessage`Product combo new` },
  [EventType.WorkspaceBranchArchived]: { name: defineMessage`Workspace branch archived` },
  [EventType.LoansChangeWorkspaceBranch]: { name: defineMessage`Change loan workspace branch` },
  [EventType.ReceiptChangeWorkspaceBranch]: {
    name: defineMessage`Change receipt workspace branch`,
  },
  [EventType.WorkspaceApiAppCreated]: { name: defineMessage`API App created` },
  [EventType.WorkspaceApiAppUpdated]: { name: defineMessage`API App updated` },
  [EventType.WorkspaceApiAppArchived]: { name: defineMessage`API App archived` },
  [EventType.ReportRealtimeSynced]: { name: defineMessage`Report realtime synced` },
  [EventType.CustomerFormNew]: { name: defineMessage`New customer form` },
  [EventType.CustomerFormUpdated]: { name: defineMessage`Customer form updated` },
  [EventType.CustomerFormArchived]: { name: defineMessage`Customer form archived` },
  [EventType.TaskSynced]: { name: defineMessage`Task synced` },
  [EventType.ReceiptSynced]: { name: defineMessage`Receipt synced` },
  [EventType.PostNew]: { name: defineMessage`Post created` },
  [EventType.PostUpdated]: { name: defineMessage`Post updated` },
  [EventType.PostArchived]: { name: defineMessage`Post archived` },
  [EventType.CategoryNew]: { name: defineMessage`Category created` },
  [EventType.CategoryUpdated]: { name: defineMessage`Category updated` },
  [EventType.CategoryArchived]: { name: defineMessage`Category archived` },
  [EventType.PromotionNew]: { name: defineMessage`Promotion created` },
  [EventType.PromotionUpdated]: { name: defineMessage`Promotion updated` },
  [EventType.PromotionArchived]: { name: defineMessage`Promotion archived` },
  [EventType.LoansApprovedReverted]: { name: defineMessage`Loan approved reverted` },
  [EventType.ReceiptRevertPayment]: { name: defineMessage`Receipt revert payment` },
  [EventType.LoansRevertRejected]: { name: defineMessage`Loan rejected reverted` },
  [EventType.WorkspaceMemberOnline]: { name: defineMessage`Workspace member online` },
  [EventType.WorkspaceMemberOffline]: { name: defineMessage`Workspace member offline` },
  [EventType.UserOnline]: { name: defineMessage`User online` },
  [EventType.UserOffline]: { name: defineMessage`User offline` },
  [EventType.LoansFulfilledReverted]: { name: defineMessage`Loan fulfilled reverted` },
  [EventType.WorkspaceStatsUpdated]: { name: defineMessage`Workspace stats updated` },
  [EventType.EInvoiceCreated]: { name: defineMessage`E-invoice created` },
  [EventType.EInvoiceRemoved]: { name: defineMessage`E-invoice removed` },
};
