#import "../../workspace-members/graphql/fragmentWorkspaceMember.graphql"

query ProductStocks($limit: Float, $offset: Float, $query: JSONObject) {
  productStocks(limit: $limit, offset: $offset, query: $query) {
    total
    results {
      refs
      createdAt
      updatedAt
      id
      _count
      _id
      code
      productId
      product {
        _id
        name
      }
      quantity
      remainQuantity
      expireAt
      costPrice
      note
      records
      createdByUser {
        ...WorkspaceMemberData       
      }
    }
  }
}